In [35]:
import pandas as pd
import io
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(io.BytesIO(uploaded['Outfielders.csv']))

Saving Outfielders.csv to Outfielders (1).csv

In [36]:
pd.set_option('display.max_columns', 500)

In [37]:
#Impute all NA values with 0
df.fillna(value = 0, inplace = True)

In [38]:
df.head()

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,G+A,G_minus_PK,PK,PKatt,CrdY,CrdR,xG_Expected,npxG_Expected,xAG_Expected,npxG+xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per,Ast_Per,G+A_Per,G_minus_PK_Per,G+A_minus_PK_Per,xG_Per,xAG_Per,xG+xAG_Per,npxG_Per,npxG+xAG_Per,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Tkl_percent_Challenges,Lost_Challenges,Blocks_Blocks,Sh_Blocks,Pass_Blocks,Int,Tkl+Int,Clr,Err,Cmp_Total,Att_Total,Cmp_percent_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_percent_Short,Cmp_Medium,Att_Medium,Cmp_percent_Medium,Cmp_Long,Att_Long,Cmp_percent_Long,xAG,xA,A_minus_xAG,KP,Final_Third,PPA,CrsPA,PrgP,Gls_Standard,Sh_Standard,SoT_Standard,SoT_percent_Standard,Sh_per_90_Standard,SoT_per_90_Standard,G_per_Sh_Standard,G_per_SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,npxG_per_Sh_Expected,G_minus_xG_Expected,np:G_minus_xG_Expected,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,SCA90_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,GCA90_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Succ_percent_Take,Tkld_Take,Tkld_percent_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,PrgC_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,PrgR_Receiving,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Won_percent_Aerial
0,2023,Ajaccio,Ligue 1,Mickaël Alphonse,GLP,DF,34,1989,26,14,1361,0,0,0,0,0,0,2,1,0.5,0.5,0.7,1.2,30.0,51.0,34.0,0.00,0.00,0.00,0.00,0.00,0.03,0.04,0.08,0.03,0.08,15.1,35.0,23,20.0,11.0,4.0,20.0,33.0,60.6,13.0,17.0,5.0,12.0,35,70.0,44.0,1.0,448.0,686.0,65.3,7834.0,3413.0,197.0,237.0,83.1,190.0,272.0,69.9,45.0,133.0,33.8,0.7,0.9,-0.7,11.0,43.0,10.0,5.0,51.0,0,10,2,20.0,0.66,0.13,0.00,0.00,16.3,0.0,0,0,0.05,-0.5,-0.5,686.0,527.0,157.0,8.0,0.0,0.0,27,149.0,0.0,0.0,0.0,0.0,448.0,2.0,21.0,19.0,1.25,15.0,1.0,1.0,1.0,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,879.0,54.0,255.0,457.0,178.0,13.0,879.0,19.0,10.0,52.6,8.0,42.1,473.0,2988.0,1528.0,30.0,25.0,0.0,15.0,14.0,403.0,34.0,0,19,15,0,27,23,0.0,1.0,1,89.0,32.0,27.0,54.2
1,2023,Ajaccio,Ligue 1,Cédric Avinel,GLP,DF,37,1986,24,19,1794,1,0,1,1,0,0,2,1,1.0,1.0,0.0,1.0,3.0,31.0,1.0,0.05,0.00,0.05,0.05,0.05,0.05,0.00,0.05,0.05,0.05,19.9,13.0,7,8.0,5.0,0.0,8.0,12.0,66.7,4.0,20.0,13.0,7.0,15,28.0,91.0,1.0,607.0,714.0,85.0,12003.0,4107.0,174.0,194.0,89.7,346.0,388.0,89.2,71.0,108.0,65.7,0.0,0.1,0.0,0.0,13.0,0.0,0.0,31.0,1,3,1,33.3,0.15,0.05,0.33,1.00,4.1,0.0,0,0,0.41,0.0,0.0,714.0,693.0,21.0,21.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,607.0,0.0,2.0,3.0,0.15,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.05,0.0,0.0,0.0,1.0,0.0,0.0,876.0,119.0,508.0,369.0,5.0,2.0,876.0,1.0,0.0,0.0,0.0,0.0,576.0,3235.0,1495.0,3.0,1.0,0.0,3.0,0.0,508.0,1.0,0,12,2,0,0,7,0.0,2.0,0,93.0,38.0,15.0,71.7
2,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,32,1991,20,15,1325,1,1,2,1,0,0,1,0,0.9,0.9,1.9,2.8,26.0,87.0,53.0,0.07,0.07,0.14,0.07,0.14,0.06,0.13,0.19,0.06,0.19,14.7,32.0,20,12.0,17.0,3.0,8.0,45.0,17.8,37.0,17.0,0.0,17.0,18,50.0,11.0,0.0,481.0,695.0,69.2,9089.0,3373.0,205.0,247.0,83.0,179.0,239.0,74.9,80.0,173.0,46.2,1.9,2.1,-0.9,18.0,71.0,16.0,7.0,87.0,1,19,4,21.1,1.29,0.27,0.05,0.25,26.6,3.0,0,0,0.05,0.1,0.1,695.0,607.0,83.0,46.0,2.0,4.0,76,12.0,24.0,9.0,11.0,0.0,481.0,5.0,14.0,30.0,2.04,22.0,7.0,0.0,0.0,0.0,1.0,1.0,0.07,1.0,0.0,0.0,0.0,0.0,0.0,869.0,18.0,159.0,501.0,227.0,9.0,869.0,49.0,23.0,46.9,24.0,49.0,601.0,3671.0,1576.0,26.0,30.0,0.0,34.0,19.0,533.0,53.0,0,20,8,0,76,20,0.0,0.0,0,100.0,9.0,7.0,56.3
3,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,27,1996,33,25,2009,1,1,2,1,0,0,3,1,2.0,2.0,2.0,4.1,46.0,66.0,109.0,0.04,0.04,0.09,0.04,0.09,0.09,0.09,0.18,0.09,0.18,22.3,53.0,37,16.0,20.0,17.0,23.0,47.0,48.9,24.0,20.0,3.0,17.0,25,78.0,21.0,0.0,399.0,654.0,61.0,6041.0,2291.0,219.0,290.0,75.5,133.0,215.0,61.9,24.0,76.0,31.6,2.0,1.7,-1.0,19.0,45.0,14.0,7.0,66.0,1,22,6,27.3,0.99,0.27,0.05,0.17,15.2,0.0,0,0,0.09,-1.0,-1.0,654.0,615.0,35.0,1.0,5.0,0.0,44,34.0,0.0,0.0,0.0,0.0,399.0,4.0,32.0,43.0,1.93,29.0,1.0,4.0,1.0,4.0,4.0,2.0,0.09,1.0,0.0,0.0,0.0,0.0,1.0,947.0,27.0,161.0,431.0,373.0,45.0,947.0,68.0,25.0,36.8,38.0,55.9,620.0,4019.0,1631.0,46.0,34.0,14.0,56.0,35.0,541.0,109.0,0,29,28,7,44,37,0.0,0.0,0,150.0,41.0,57.0,41.8
4,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,"MF,FW",31,1992,17,15,1150,6,3,9,1,5,6,2,0,6.2,1.8,3.5,5.3,32.0,55.0,68.0,0.47,0.23,0.70,0.08,0.31,0.48,0.27,0.76,0.14,0.42,12.8,18.0,10,3.0,9.0,6.0,8.0,20.0,40.0,12.0,10.0,1.0,9.0,5,23.0,4.0,0.0,328.0,458.0,71.6,5637.0,2159.0,162.0,201.0,80.6,101.0,137.0,73.7,44.0,74.0,59.5,3.5,3.3,-0.5,21.0,35.0,22.0,6.0,55.0,6,27,9,33.3,2.11,0.70,0.04,0.11,24.8,4.0,5,6,0.07,-0.2,-0.8,458.0,397.0,56.0,22.0,5.0,2.0,42,12.0,15.0,4.0,6.0,0.0,328.0,5.0,13.0,47.0,3.68,24.0,9.0,4.0,4.0,6.0,0.0,10.0,0.78,5.0,0.0,2.0,1.0,2.0,0.0,631.0,6.0,66.0,320.0,257.0,51.0,625.0,64.0,29.0,45.3,24.0,37.5,476.0,3115.0,1319.0,32.0,24.0,18.0,42.0,27.0,431.0,68.0,0,25,24,4,42,10,2.0,0.0,0,75.0,7.0,9.0,43.8

## Some of the Players Do Not Have a Nation. We Can Set These Nations to Be ‘Unknown'

In [39]:
for i in range(len(df)):
  if df.loc[i, 'Nation'] == 0:
    df.loc[i, 'Nation'] == 'Unknown'

In [40]:
import numpy as np

In [41]:
df.head()

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,G+A,G_minus_PK,PK,PKatt,CrdY,CrdR,xG_Expected,npxG_Expected,xAG_Expected,npxG+xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Gls_Per,Ast_Per,G+A_Per,G_minus_PK_Per,G+A_minus_PK_Per,xG_Per,xAG_Per,xG+xAG_Per,npxG_Per,npxG+xAG_Per,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Tkl_percent_Challenges,Lost_Challenges,Blocks_Blocks,Sh_Blocks,Pass_Blocks,Int,Tkl+Int,Clr,Err,Cmp_Total,Att_Total,Cmp_percent_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_percent_Short,Cmp_Medium,Att_Medium,Cmp_percent_Medium,Cmp_Long,Att_Long,Cmp_percent_Long,xAG,xA,A_minus_xAG,KP,Final_Third,PPA,CrsPA,PrgP,Gls_Standard,Sh_Standard,SoT_Standard,SoT_percent_Standard,Sh_per_90_Standard,SoT_per_90_Standard,G_per_Sh_Standard,G_per_SoT_Standard,Dist_Standard,FK_Standard,PK_Standard,PKatt_Standard,npxG_per_Sh_Expected,G_minus_xG_Expected,np:G_minus_xG_Expected,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,SCA90_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,GCA90_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Succ_percent_Take,Tkld_Take,Tkld_percent_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,PrgC_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,PrgR_Receiving,2CrdY,Fls,Fld,Off,Crs,TklW,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Won_percent_Aerial
0,2023,Ajaccio,Ligue 1,Mickaël Alphonse,GLP,DF,34,1989,26,14,1361,0,0,0,0,0,0,2,1,0.5,0.5,0.7,1.2,30.0,51.0,34.0,0.00,0.00,0.00,0.00,0.00,0.03,0.04,0.08,0.03,0.08,15.1,35.0,23,20.0,11.0,4.0,20.0,33.0,60.6,13.0,17.0,5.0,12.0,35,70.0,44.0,1.0,448.0,686.0,65.3,7834.0,3413.0,197.0,237.0,83.1,190.0,272.0,69.9,45.0,133.0,33.8,0.7,0.9,-0.7,11.0,43.0,10.0,5.0,51.0,0,10,2,20.0,0.66,0.13,0.00,0.00,16.3,0.0,0,0,0.05,-0.5,-0.5,686.0,527.0,157.0,8.0,0.0,0.0,27,149.0,0.0,0.0,0.0,0.0,448.0,2.0,21.0,19.0,1.25,15.0,1.0,1.0,1.0,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,879.0,54.0,255.0,457.0,178.0,13.0,879.0,19.0,10.0,52.6,8.0,42.1,473.0,2988.0,1528.0,30.0,25.0,0.0,15.0,14.0,403.0,34.0,0,19,15,0,27,23,0.0,1.0,1,89.0,32.0,27.0,54.2
1,2023,Ajaccio,Ligue 1,Cédric Avinel,GLP,DF,37,1986,24,19,1794,1,0,1,1,0,0,2,1,1.0,1.0,0.0,1.0,3.0,31.0,1.0,0.05,0.00,0.05,0.05,0.05,0.05,0.00,0.05,0.05,0.05,19.9,13.0,7,8.0,5.0,0.0,8.0,12.0,66.7,4.0,20.0,13.0,7.0,15,28.0,91.0,1.0,607.0,714.0,85.0,12003.0,4107.0,174.0,194.0,89.7,346.0,388.0,89.2,71.0,108.0,65.7,0.0,0.1,0.0,0.0,13.0,0.0,0.0,31.0,1,3,1,33.3,0.15,0.05,0.33,1.00,4.1,0.0,0,0,0.41,0.0,0.0,714.0,693.0,21.0,21.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,607.0,0.0,2.0,3.0,0.15,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.05,0.0,0.0,0.0,1.0,0.0,0.0,876.0,119.0,508.0,369.0,5.0,2.0,876.0,1.0,0.0,0.0,0.0,0.0,576.0,3235.0,1495.0,3.0,1.0,0.0,3.0,0.0,508.0,1.0,0,12,2,0,0,7,0.0,2.0,0,93.0,38.0,15.0,71.7
2,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,32,1991,20,15,1325,1,1,2,1,0,0,1,0,0.9,0.9,1.9,2.8,26.0,87.0,53.0,0.07,0.07,0.14,0.07,0.14,0.06,0.13,0.19,0.06,0.19,14.7,32.0,20,12.0,17.0,3.0,8.0,45.0,17.8,37.0,17.0,0.0,17.0,18,50.0,11.0,0.0,481.0,695.0,69.2,9089.0,3373.0,205.0,247.0,83.0,179.0,239.0,74.9,80.0,173.0,46.2,1.9,2.1,-0.9,18.0,71.0,16.0,7.0,87.0,1,19,4,21.1,1.29,0.27,0.05,0.25,26.6,3.0,0,0,0.05,0.1,0.1,695.0,607.0,83.0,46.0,2.0,4.0,76,12.0,24.0,9.0,11.0,0.0,481.0,5.0,14.0,30.0,2.04,22.0,7.0,0.0,0.0,0.0,1.0,1.0,0.07,1.0,0.0,0.0,0.0,0.0,0.0,869.0,18.0,159.0,501.0,227.0,9.0,869.0,49.0,23.0,46.9,24.0,49.0,601.0,3671.0,1576.0,26.0,30.0,0.0,34.0,19.0,533.0,53.0,0,20,8,0,76,20,0.0,0.0,0,100.0,9.0,7.0,56.3
3,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,27,1996,33,25,2009,1,1,2,1,0,0,3,1,2.0,2.0,2.0,4.1,46.0,66.0,109.0,0.04,0.04,0.09,0.04,0.09,0.09,0.09,0.18,0.09,0.18,22.3,53.0,37,16.0,20.0,17.0,23.0,47.0,48.9,24.0,20.0,3.0,17.0,25,78.0,21.0,0.0,399.0,654.0,61.0,6041.0,2291.0,219.0,290.0,75.5,133.0,215.0,61.9,24.0,76.0,31.6,2.0,1.7,-1.0,19.0,45.0,14.0,7.0,66.0,1,22,6,27.3,0.99,0.27,0.05,0.17,15.2,0.0,0,0,0.09,-1.0,-1.0,654.0,615.0,35.0,1.0,5.0,0.0,44,34.0,0.0,0.0,0.0,0.0,399.0,4.0,32.0,43.0,1.93,29.0,1.0,4.0,1.0,4.0,4.0,2.0,0.09,1.0,0.0,0.0,0.0,0.0,1.0,947.0,27.0,161.0,431.0,373.0,45.0,947.0,68.0,25.0,36.8,38.0,55.9,620.0,4019.0,1631.0,46.0,34.0,14.0,56.0,35.0,541.0,109.0,0,29,28,7,44,37,0.0,0.0,0,150.0,41.0,57.0,41.8
4,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,"MF,FW",31,1992,17,15,1150,6,3,9,1,5,6,2,0,6.2,1.8,3.5,5.3,32.0,55.0,68.0,0.47,0.23,0.70,0.08,0.31,0.48,0.27,0.76,0.14,0.42,12.8,18.0,10,3.0,9.0,6.0,8.0,20.0,40.0,12.0,10.0,1.0,9.0,5,23.0,4.0,0.0,328.0,458.0,71.6,5637.0,2159.0,162.0,201.0,80.6,101.0,137.0,73.7,44.0,74.0,59.5,3.5,3.3,-0.5,21.0,35.0,22.0,6.0,55.0,6,27,9,33.3,2.11,0.70,0.04,0.11,24.8,4.0,5,6,0.07,-0.2,-0.8,458.0,397.0,56.0,22.0,5.0,2.0,42,12.0,15.0,4.0,6.0,0.0,328.0,5.0,13.0,47.0,3.68,24.0,9.0,4.0,4.0,6.0,0.0,10.0,0.78,5.0,0.0,2.0,1.0,2.0,0.0,631.0,6.0,66.0,320.0,257.0,51.0,625.0,64.0,29.0,45.3,24.0,37.5,476.0,3115.0,1319.0,32.0,24.0,18.0,42.0,27.0,431.0,68.0,0,25,24,4,42,10,2.0,0.0,0,75.0,7.0,9.0,43.8

## Now We Drop Unnecessary Columns

In [42]:
#We need to remove columns that contain percentages as these are calculated based off of some of the existing columns. So we don't need them
for i in list(df.columns):
  if 'percent' in i:
    print(i)

Tkl_percent_Challenges
Cmp_percent_Total
Cmp_percent_Short
Cmp_percent_Medium
Cmp_percent_Long
SoT_percent_Standard
Succ_percent_Take
Tkld_percent_Take
Won_percent_Aerial

In [43]:
print(list(df.columns))

['Season_End_Year', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'Born', 'MP_Playing', 'Starts_Playing', 'Min_Playing', 'Gls', 'Ast', 'G+A', 'G_minus_PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'npxG+xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Gls_Per', 'Ast_Per', 'G+A_Per', 'G_minus_PK_Per', 'G+A_minus_PK_Per', 'xG_Per', 'xAG_Per', 'xG+xAG_Per', 'npxG_Per', 'npxG+xAG_Per', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Tkl_percent_Challenges', 'Lost_Challenges', 'Blocks_Blocks', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Tkl+Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'Cmp_percent_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_percent_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_percent_Medium', 'Cmp_Long', 'Att_Long', 'Cmp_percent_Long', 'xAG', 'xA', 'A_minus_xAG', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'PrgP', 'Gls_Standard', 'Sh_Standard', 'SoT_Standard', 'SoT_percent_Standard', 'Sh_per_90_Standard', 'SoT_per_90_Standard', 'G_per_Sh_Standard', 'G_per_SoT_Standard', 'Dist_Standard', 'FK_Standard', 'PK_Standard', 'PKatt_Standard', 'npxG_per_Sh_Expected', 'G_minus_xG_Expected', 'np:G_minus_xG_Expected', 'Att', 'Live_Pass', 'Dead_Pass', 'FK_Pass', 'TB_Pass', 'Sw_Pass', 'Crs_Pass', 'TI_Pass', 'CK_Pass', 'In_Corner', 'Out_Corner', 'Str_Corner', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'SCA90_SCA', 'PassLive_SCA', 'PassDead_SCA', 'TO_SCA', 'Sh_SCA', 'Fld_SCA', 'Def_SCA', 'GCA_GCA', 'GCA90_GCA', 'PassLive_GCA', 'PassDead_GCA', 'TO_GCA', 'Sh_GCA', 'Fld_GCA', 'Def_GCA', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take', 'Succ_Take', 'Succ_percent_Take', 'Tkld_Take', 'Tkld_percent_Take', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'PrgC_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'PrgR_Receiving', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial', 'Lost_Aerial', 'Won_percent_Aerial']

In [44]:
#Drop some more Unnecessary Columns
df.drop(columns = ['npxG_per_Sh_Expected', 'G_per_SoT_Standard', 'G_per_Sh_Standard', 'SoT_percent_Standard', 'Cmp_percent_Long', 'Cmp_percent_Medium', 'Cmp_percent_Short', 'Cmp_percent_Total', 'Tkl_percent_Challenges', 'G+A', 'npxG+xAG_Expected', 'G_minus_xG_Expected', 'G_minus_PK', 'CrdR', 'CrdY', 'A_minus_xAG', 'np:G_minus_xG_Expected', 'Blocks_Blocks', 'Tkl+Int', 'Gls_Per', 'Ast_Per', 'G+A_Per', 'PK_Standard', 'PKatt_Standard', 'G_minus_PK_Per', 'G+A_minus_PK_Per', 'xG_Per', 'xAG_Per', 'xG+xAG_Per', 'npxG_Per', 'npxG+xAG_Per', 'xAG', 'PrgP', 'Gls_Standard', 'Sh_per_90_Standard', 'SoT_per_90_Standard', 'Succ_percent_Take', 'Tkld_percent_Take', 'Won_percent_Aerial'], inplace = True)

In [45]:
print(list(df.columns))

['Season_End_Year', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'Born', 'MP_Playing', 'Starts_Playing', 'Min_Playing', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'Att', 'Live_Pass', 'Dead_Pass', 'FK_Pass', 'TB_Pass', 'Sw_Pass', 'Crs_Pass', 'TI_Pass', 'CK_Pass', 'In_Corner', 'Out_Corner', 'Str_Corner', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'SCA90_SCA', 'PassLive_SCA', 'PassDead_SCA', 'TO_SCA', 'Sh_SCA', 'Fld_SCA', 'Def_SCA', 'GCA_GCA', 'GCA90_GCA', 'PassLive_GCA', 'PassDead_GCA', 'TO_GCA', 'Sh_GCA', 'Fld_GCA', 'Def_GCA', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take', 'Succ_Take', 'Tkld_Take', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'PrgC_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'PrgR_Receiving', '2CrdY', 'Fls', 'Fld', 'Off', 'Crs', 'TklW', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial', 'Lost_Aerial']

In [46]:
#Drop Unnecessary Columns
df.drop(columns = ['SCA90_SCA', 'GCA90_GCA', 'PrgC_Carries', 'PrgR_Receiving', '2CrdY', 'TklW'], inplace = True)

In [47]:
df.head()

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial
0,2023,Ajaccio,Ligue 1,Mickaël Alphonse,GLP,DF,34,1989,26,14,1361,0,0,0,0,0.5,0.5,0.7,30.0,51.0,34.0,15.1,35.0,23,20.0,11.0,4.0,20.0,33.0,13.0,5.0,12.0,35,44.0,1.0,448.0,686.0,7834.0,3413.0,197.0,237.0,190.0,272.0,45.0,133.0,0.9,11.0,43.0,10.0,5.0,10,2,16.3,0.0,686.0,527.0,157.0,8.0,0.0,0.0,27,149.0,0.0,0.0,0.0,0.0,448.0,2.0,21.0,19.0,15.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,879.0,54.0,255.0,457.0,178.0,13.0,879.0,19.0,10.0,8.0,473.0,2988.0,1528.0,25.0,0.0,15.0,14.0,403.0,19,15,0,27,0.0,1.0,1,89.0,32.0,27.0
1,2023,Ajaccio,Ligue 1,Cédric Avinel,GLP,DF,37,1986,24,19,1794,1,0,0,0,1.0,1.0,0.0,3.0,31.0,1.0,19.9,13.0,7,8.0,5.0,0.0,8.0,12.0,4.0,13.0,7.0,15,91.0,1.0,607.0,714.0,12003.0,4107.0,174.0,194.0,346.0,388.0,71.0,108.0,0.1,0.0,13.0,0.0,0.0,3,1,4.1,0.0,714.0,693.0,21.0,21.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,607.0,0.0,2.0,3.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,876.0,119.0,508.0,369.0,5.0,2.0,876.0,1.0,0.0,0.0,576.0,3235.0,1495.0,1.0,0.0,3.0,0.0,508.0,12,2,0,0,0.0,2.0,0,93.0,38.0,15.0
2,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,32,1991,20,15,1325,1,1,0,0,0.9,0.9,1.9,26.0,87.0,53.0,14.7,32.0,20,12.0,17.0,3.0,8.0,45.0,37.0,0.0,17.0,18,11.0,0.0,481.0,695.0,9089.0,3373.0,205.0,247.0,179.0,239.0,80.0,173.0,2.1,18.0,71.0,16.0,7.0,19,4,26.6,3.0,695.0,607.0,83.0,46.0,2.0,4.0,76,12.0,24.0,9.0,11.0,0.0,481.0,5.0,14.0,30.0,22.0,7.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,869.0,18.0,159.0,501.0,227.0,9.0,869.0,49.0,23.0,24.0,601.0,3671.0,1576.0,30.0,0.0,34.0,19.0,533.0,20,8,0,76,0.0,0.0,0,100.0,9.0,7.0
3,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,27,1996,33,25,2009,1,1,0,0,2.0,2.0,2.0,46.0,66.0,109.0,22.3,53.0,37,16.0,20.0,17.0,23.0,47.0,24.0,3.0,17.0,25,21.0,0.0,399.0,654.0,6041.0,2291.0,219.0,290.0,133.0,215.0,24.0,76.0,1.7,19.0,45.0,14.0,7.0,22,6,15.2,0.0,654.0,615.0,35.0,1.0,5.0,0.0,44,34.0,0.0,0.0,0.0,0.0,399.0,4.0,32.0,43.0,29.0,1.0,4.0,1.0,4.0,4.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,947.0,27.0,161.0,431.0,373.0,45.0,947.0,68.0,25.0,38.0,620.0,4019.0,1631.0,34.0,14.0,56.0,35.0,541.0,29,28,7,44,0.0,0.0,0,150.0,41.0,57.0
4,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,"MF,FW",31,1992,17,15,1150,6,3,5,6,6.2,1.8,3.5,32.0,55.0,68.0,12.8,18.0,10,3.0,9.0,6.0,8.0,20.0,12.0,1.0,9.0,5,4.0,0.0,328.0,458.0,5637.0,2159.0,162.0,201.0,101.0,137.0,44.0,74.0,3.3,21.0,35.0,22.0,6.0,27,9,24.8,4.0,458.0,397.0,56.0,22.0,5.0,2.0,42,12.0,15.0,4.0,6.0,0.0,328.0,5.0,13.0,47.0,24.0,9.0,4.0,4.0,6.0,0.0,10.0,5.0,0.0,2.0,1.0,2.0,0.0,631.0,6.0,66.0,320.0,257.0,51.0,625.0,64.0,29.0,24.0,476.0,3115.0,1319.0,24.0,18.0,42.0,27.0,431.0,25,24,4,42,2.0,0.0,0,75.0,7.0,9.0

## Now, Some Players Who Are From the Same Nation and Have the Same Age Are Present. We Need to Rename One of Them So as to Avoid Merging Them Accidentally. (We Will Look at Why Merging Is Done Later On).

In [48]:
#There are 2 players named Vitinha who have the same name and age.
df.loc[(df['Player'] == 'Vitinha') ]

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial
1556,2023,Marseille,Ligue 1,Vitinha,POR,FW,23,2000,14,5,464,2,0,0,0,4.0,4.0,0.2,3.0,9.0,41.0,5.2,15.0,7,0.0,6.0,9.0,3.0,11.0,8.0,0.0,3.0,2,6.0,0.0,77.0,109.0,1023.0,231.0,46.0,61.0,21.0,26.0,3.0,4.0,0.2,3.0,7.0,2.0,0.0,25,9,12.6,0.0,109.0,96.0,11.0,1.0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0,77.0,2.0,4.0,11.0,5.0,0.0,3.0,2.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,198.0,6.0,14.0,82.0,107.0,42.0,198.0,11.0,5.0,6.0,133.0,615.0,191.0,6.0,2.0,18.0,8.0,121.0,7,8,4,1,0.0,0.0,0,27.0,5.0,13.0
1851,2023,Paris S-G,Ligue 1,Vitinha,POR,MF,23,2000,36,29,2446,2,3,0,0,3.0,3.0,3.0,50.0,137.0,94.0,27.2,58.0,25,21.0,27.0,10.0,27.0,83.0,56.0,4.0,23.0,25,15.0,0.0,1786.0,1945.0,26148.0,5772.0,960.0,1018.0,613.0,657.0,95.0,113.0,3.4,27.0,170.0,24.0,1.0,31,11,20.5,0.0,1945.0,1923.0,18.0,9.0,7.0,6.0,13,3.0,6.0,2.0,3.0,0.0,1786.0,4.0,26.0,73.0,63.0,2.0,0.0,4.0,2.0,2.0,10.0,8.0,0.0,0.0,1.0,1.0,0.0,2189.0,41.0,325.0,1299.0,584.0,38.0,2189.0,53.0,31.0,17.0,1872.0,9931.0,4552.0,74.0,5.0,33.0,33.0,1786.0,31,19,0,13,0.0,0.0,0,164.0,5.0,4.0

In [49]:
#Rename the Vitinha playing for Marseille as follows.
df.loc[1556, 'Player'] = 'Vitinha Vitor Oliveira'

##Now, There Are Some Players Who Are Transferred in the January Transfer Window. Since We Want Each Row to Represent a Unique Player, We Need to Sum Up the Stats of the Transferred Players. This Is Where Merging Comes Into Play and We Do So by Creating a Primary Key Called ‘Temp’ Which Contatenates the Values of ‘Player’, ‘Nation’, ‘Age’, and ‘Born’ (i.e. Birth Year)

In [50]:
df['temp'] = df['Player'].map(str) + df['Nation'].map(str) + df['Age'].map(str) + df['Born'].map(str)

In [51]:
df.head()

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,temp
0,2023,Ajaccio,Ligue 1,Mickaël Alphonse,GLP,DF,34,1989,26,14,1361,0,0,0,0,0.5,0.5,0.7,30.0,51.0,34.0,15.1,35.0,23,20.0,11.0,4.0,20.0,33.0,13.0,5.0,12.0,35,44.0,1.0,448.0,686.0,7834.0,3413.0,197.0,237.0,190.0,272.0,45.0,133.0,0.9,11.0,43.0,10.0,5.0,10,2,16.3,0.0,686.0,527.0,157.0,8.0,0.0,0.0,27,149.0,0.0,0.0,0.0,0.0,448.0,2.0,21.0,19.0,15.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,879.0,54.0,255.0,457.0,178.0,13.0,879.0,19.0,10.0,8.0,473.0,2988.0,1528.0,25.0,0.0,15.0,14.0,403.0,19,15,0,27,0.0,1.0,1,89.0,32.0,27.0,Mickaël AlphonseGLP341989
1,2023,Ajaccio,Ligue 1,Cédric Avinel,GLP,DF,37,1986,24,19,1794,1,0,0,0,1.0,1.0,0.0,3.0,31.0,1.0,19.9,13.0,7,8.0,5.0,0.0,8.0,12.0,4.0,13.0,7.0,15,91.0,1.0,607.0,714.0,12003.0,4107.0,174.0,194.0,346.0,388.0,71.0,108.0,0.1,0.0,13.0,0.0,0.0,3,1,4.1,0.0,714.0,693.0,21.0,21.0,0.0,1.0,0,0.0,0.0,0.0,0.0,0.0,607.0,0.0,2.0,3.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,876.0,119.0,508.0,369.0,5.0,2.0,876.0,1.0,0.0,0.0,576.0,3235.0,1495.0,1.0,0.0,3.0,0.0,508.0,12,2,0,0,0.0,2.0,0,93.0,38.0,15.0,Cédric AvinelGLP371986
2,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,32,1991,20,15,1325,1,1,0,0,0.9,0.9,1.9,26.0,87.0,53.0,14.7,32.0,20,12.0,17.0,3.0,8.0,45.0,37.0,0.0,17.0,18,11.0,0.0,481.0,695.0,9089.0,3373.0,205.0,247.0,179.0,239.0,80.0,173.0,2.1,18.0,71.0,16.0,7.0,19,4,26.6,3.0,695.0,607.0,83.0,46.0,2.0,4.0,76,12.0,24.0,9.0,11.0,0.0,481.0,5.0,14.0,30.0,22.0,7.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,869.0,18.0,159.0,501.0,227.0,9.0,869.0,49.0,23.0,24.0,601.0,3671.0,1576.0,30.0,0.0,34.0,19.0,533.0,20,8,0,76,0.0,0.0,0,100.0,9.0,7.0,Mickaël BarretoFRA321991
3,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,27,1996,33,25,2009,1,1,0,0,2.0,2.0,2.0,46.0,66.0,109.0,22.3,53.0,37,16.0,20.0,17.0,23.0,47.0,24.0,3.0,17.0,25,21.0,0.0,399.0,654.0,6041.0,2291.0,219.0,290.0,133.0,215.0,24.0,76.0,1.7,19.0,45.0,14.0,7.0,22,6,15.2,0.0,654.0,615.0,35.0,1.0,5.0,0.0,44,34.0,0.0,0.0,0.0,0.0,399.0,4.0,32.0,43.0,29.0,1.0,4.0,1.0,4.0,4.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,947.0,27.0,161.0,431.0,373.0,45.0,947.0,68.0,25.0,38.0,620.0,4019.0,1631.0,34.0,14.0,56.0,35.0,541.0,29,28,7,44,0.0,0.0,0,150.0,41.0,57.0,Cyrille BayalaBFA271996
4,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,"MF,FW",31,1992,17,15,1150,6,3,5,6,6.2,1.8,3.5,32.0,55.0,68.0,12.8,18.0,10,3.0,9.0,6.0,8.0,20.0,12.0,1.0,9.0,5,4.0,0.0,328.0,458.0,5637.0,2159.0,162.0,201.0,101.0,137.0,44.0,74.0,3.3,21.0,35.0,22.0,6.0,27,9,24.8,4.0,458.0,397.0,56.0,22.0,5.0,2.0,42,12.0,15.0,4.0,6.0,0.0,328.0,5.0,13.0,47.0,24.0,9.0,4.0,4.0,6.0,0.0,10.0,5.0,0.0,2.0,1.0,2.0,0.0,631.0,6.0,66.0,320.0,257.0,51.0,625.0,64.0,29.0,24.0,476.0,3115.0,1319.0,24.0,18.0,42.0,27.0,431.0,25,24,4,42,2.0,0.0,0,75.0,7.0,9.0,Youcef BelaïliALG311992

In [52]:
#Create a Copy of the Dataframe
y = df.copy()

In [53]:
print(list(df.columns))

['Season_End_Year', 'Squad', 'Comp', 'Player', 'Nation', 'Pos', 'Age', 'Born', 'MP_Playing', 'Starts_Playing', 'Min_Playing', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'Att', 'Live_Pass', 'Dead_Pass', 'FK_Pass', 'TB_Pass', 'Sw_Pass', 'Crs_Pass', 'TI_Pass', 'CK_Pass', 'In_Corner', 'Out_Corner', 'Str_Corner', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'PassLive_SCA', 'PassDead_SCA', 'TO_SCA', 'Sh_SCA', 'Fld_SCA', 'Def_SCA', 'GCA_GCA', 'PassLive_GCA', 'PassDead_GCA', 'TO_GCA', 'Sh_GCA', 'Fld_GCA', 'Def_GCA', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take', 'Succ_Take', 'Tkld_Take', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'Fls', 'Fld', 'Off', 'Crs', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial', 'Lost_Aerial', 'temp']

In [54]:
#Identify the Columns whose values are to be summed up for transferred players
cols = list(df.columns)[8:-1]
cols

['MP_Playing',
 'Starts_Playing',
 'Min_Playing',
 'Gls',
 'Ast',
 'PK',
 'PKatt',
 'xG_Expected',
 'npxG_Expected',
 'xAG_Expected',
 'PrgC_Progression',
 'PrgP_Progression',
 'PrgR_Progression',
 'Mins_Per_90',
 'Tkl_Tackles',
 'TklW_Tackles',
 'Def 3rd_Tackles',
 'Mid 3rd_Tackles',
 'Att 3rd_Tackles',
 'Tkl_Challenges',
 'Att_Challenges',
 'Lost_Challenges',
 'Sh_Blocks',
 'Pass_Blocks',
 'Int',
 'Clr',
 'Err',
 'Cmp_Total',
 'Att_Total',
 'TotDist_Total',
 'PrgDist_Total',
 'Cmp_Short',
 'Att_Short',
 'Cmp_Medium',
 'Att_Medium',
 'Cmp_Long',
 'Att_Long',
 'xA',
 'KP',
 'Final_Third',
 'PPA',
 'CrsPA',
 'Sh_Standard',
 'SoT_Standard',
 'Dist_Standard',
 'FK_Standard',
 'Att',
 'Live_Pass',
 'Dead_Pass',
 'FK_Pass',
 'TB_Pass',
 'Sw_Pass',
 'Crs_Pass',
 'TI_Pass',
 'CK_Pass',
 'In_Corner',
 'Out_Corner',
 'Str_Corner',
 'Cmp_Outcomes',
 'Off_Outcomes',
 'Blocks_Outcomes',
 'SCA_SCA',
 'PassLive_SCA',
 'PassDead_SCA',
 'TO_SCA',
 'Sh_SCA',
 'Fld_SCA',
 'Def_SCA',
 'GCA_GCA',
 'PassLive_GCA',
 'PassDead_GCA',
 'TO_GCA',
 'Sh_GCA',
 'Fld_GCA',
 'Def_GCA',
 'Touches_Touches',
 'Def Pen_Touches',
 'Def 3rd_Touches',
 'Mid 3rd_Touches',
 'Att 3rd_Touches',
 'Att Pen_Touches',
 'Live_Touches',
 'Att_Take',
 'Succ_Take',
 'Tkld_Take',
 'Carries_Carries',
 'TotDist_Carries',
 'PrgDist_Carries',
 'Final_Third_Carries',
 'CPA_Carries',
 'Mis_Carries',
 'Dis_Carries',
 'Rec_Receiving',
 'Fls',
 'Fld',
 'Off',
 'Crs',
 'PKwon',
 'PKcon',
 'OG',
 'Recov',
 'Won_Aerial',
 'Lost_Aerial']

##Now We Perfrom the Merging Using the Groupby() Function

In [55]:
y = y.groupby(['temp', 'Player', 'Nation', 'Age', 'Born'])[cols].sum().reset_index()
y

,temp,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial
0,Aaron CresswellENG341989,Aaron Cresswell,ENG,34,1989,28,24,2235,0,1,0,0,0.3,0.3,3.7,35.0,145.0,82.0,24.8,21.0,11,12.0,7.0,2.0,12.0,31.0,19.0,11.0,10.0,27,56.0,0.0,1127.0,1448.0,18285.0,8587.0,626.0,670.0,387.0,497.0,100.0,206.0,2.9,40.0,91.0,28.0,15.0,9,1,22.5,4.0,1448.0,1157.0,288.0,40.0,1.0,5.0,133,192.0,56.0,5.0,44.0,1.0,1127.0,3.0,35.0,73.0,43.0,27.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1607.0,97.0,507.0,668.0,438.0,13.0,1607.0,7.0,2.0,4.0,766.0,3497.0,1751.0,26.0,1.0,6.0,6.0,960.0,9,9,2,133,0.0,0.0,0,120.0,28.0,27.0
1,Aaron HickeySCO212002,Aaron Hickey,SCO,21,2002,26,23,1916,0,1,0,0,0.4,0.4,0.4,41.0,81.0,47.0,21.3,38.0,26,27.0,11.0,0.0,18.0,32.0,14.0,7.0,11.0,17,32.0,1.0,695.0,838.0,10995.0,3282.0,373.0,411.0,265.0,310.0,46.0,80.0,0.6,6.0,62.0,13.0,4.0,11,2,21.5,0.0,838.0,743.0,93.0,11.0,2.0,1.0,27,82.0,0.0,0.0,0.0,0.0,695.0,2.0,17.0,20.0,14.0,1.0,1.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1028.0,47.0,328.0,499.0,211.0,21.0,1028.0,45.0,17.0,18.0,616.0,3295.0,1802.0,17.0,3.0,16.0,13.0,624.0,20,35,1,27,0.0,1.0,0,111.0,14.0,22.0
2,Aaron RamseyWAL331990,Aaron Ramsey,WAL,33,1990,27,18,1584,1,1,0,0,2.5,2.5,1.8,29.0,126.0,84.0,17.6,47.0,25,18.0,19.0,10.0,16.0,39.0,23.0,4.0,21.0,17,18.0,1.0,915.0,1088.0,16069.0,3809.0,398.0,431.0,382.0,444.0,100.0,159.0,2.0,28.0,88.0,20.0,3.0,22,6,15.3,1.0,1088.0,998.0,88.0,37.0,5.0,11.0,62,6.0,45.0,16.0,18.0,0.0,915.0,2.0,10.0,62.0,42.0,14.0,0.0,5.0,1.0,0.0,4.0,2.0,1.0,0.0,0.0,1.0,0.0,1279.0,43.0,208.0,723.0,361.0,50.0,1279.0,24.0,14.0,5.0,980.0,4866.0,1934.0,34.0,8.0,24.0,32.0,902.0,23,18,3,62,1.0,0.0,0,115.0,6.0,12.0
3,Aaron Wan-BissakaENG261997,Aaron Wan-Bissaka,ENG,26,1997,19,16,1435,0,0,0,0,1.2,1.2,1.0,41.0,55.0,64.0,15.9,40.0,25,20.0,17.0,3.0,23.0,25.0,2.0,8.0,16.0,22,41.0,0.0,706.0,840.0,9538.0,3292.0,448.0,483.0,194.0,240.0,28.0,44.0,0.9,15.0,48.0,10.0,2.0,10,2,14.7,0.0,840.0,715.0,123.0,4.0,2.0,2.0,14,119.0,0.0,0.0,0.0,0.0,706.0,2.0,22.0,30.0,29.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1026.0,75.0,346.0,400.0,286.0,44.0,1026.0,35.0,17.0,18.0,524.0,2614.0,1370.0,24.0,4.0,14.0,10.0,600.0,11,2,0,14,0.0,0.0,0,73.0,13.0,17.0
4,Aaron ZehnterGER192004,Aaron Zehnter,GER,19,2004,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,Óscar de MarcosESP341989,Óscar de Marcos,ESP,34,1989,37,32,2819,1,6,0,0,0.4,0.4,3.5,76.0,204.0,153.0,31.3,67.0,33,34.0,22.0,11.0,40.0,76.0,36.0,6.0,36.0,29,59.0,0.0,1499.0,1932.0,25216.0,9281.0,749.0,849.0,608.0,764.0,119.0,217.0,4.5,37.0,170.0,50.0,23.0,4,2,20.3,0.0,1932.0,1552.0,372.0,32.0,0.0,11.0,130,340.0,0.0,0.0,0.0,0.0,1499.0,8.0,52.0,75.0,63.0,7.0,1.0,1.0,1.0,2.0,9.0,8.0,0.0,1.0,0.0,0.0,0.0,2218.0,93.0,525.0,1042.0,671.0,34.0,2218.0,31.0,12.0,17.0,1119.0,4785.0,2851.0,68.0,8.0,26.0,19.0,1245.0,43,16,2,130,0.0,0.0,1,198.0,25.0,23.0
2519,Þórir Jóhann HelgasonISL232000,Þórir Jóhann Helgason,ISL,23,2000,12,2,222,0,0,0,0,0.1,0.1,0.4,2.0,2.0,5.0,2.5,2.0,2,1.0,0.0,1.0,2.0,3.0,1.0,1.0,2.0,3,3.0,0.0,55.0,75.0,967.0,363.0,26.0,34.0,19.0,22.0,8.0,15.0,0.3,4.0,2.0,0.0,0.0,2,0,32.6,1.0,75.0,65.0,10.0,2.0,0.0,0.0,10,0.0,6.0,5.0,1.0,0.0,55.0,0.0,0.0,7.0,3.0,3.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,96.0,8.0,25.0,42.0,31.0,3.0,96.0,1.0,0.0,1.0,41.0,181.0,88.0,2.0,1.0,4.0,2.0,50.0,2,2,0,10,0.0,0.0,0,12.0,4.0,7.0
2520,İlkay GündoğanGER331990,İlkay Gündoğan,GER,33,1990,31,27,2353,8,4,0,1,7.5,6.7,3.3,53.0,170.0,124.0,26.1,30.0,18,7.0,13.0,10.0,12.0,33.0,21.0,3.0,15.0,20,13.0,0.0,1374.0,1578.0,21396.0,4941.0,746.0,819.0,492.0,543.0,99.0,130.0,4.4,37.0,143.0,35.0,1.0,53,20,18.1,5.0,1578.0,1519.0,56.0,24.0,18.0,6.0,30,5.0,21.0,7.0,4.0,1.0,1374.0,3.0,27.0,90.0,71.0,7.0,2.0,4.0,4.0,2.0,17.0,13.0,1.0,0.0,1.0,2.0,0.0,1806.0,31.0,243.0,975.0,596.0,88.0,1805.0,42.0,16.0,18.0,1072.0,5457.0,2628.0,44.0,7.0,28.0,27.0,1425.0,23,25,6,30,2.0,0.0,0,155.0,19.0,12.0
2521,Łukasz PorębaPOL232000,Łukasz Poręba,POL,23,2000,10,3,260,0,1,0,0,0.6,0.6,0.7,3.0,20.0,18.0,2.9,5.0,4,2.0,1.0,2.0,2.0,3.0,1.0,0.0,3.0,4,2.0,0.0,116.0,143.0,1866.0,539.0,52.0,63.0,48.0,57.0,9.0,13.0,0.4,5.0,12.0,5.0,2.0,3,0,17.1,0.0,143.0,142.0,1.0,1.0,0.0,0.0,6,0.0,0.0,0.0,0.0,0.0,116.0,0.0,1.0,9.0,8.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,170.0,4.0,20.0,93.0,57.0,1.0,170.0,2.0,1.0,1.0,126.0,625.0,223.0,8.0,0.0,5.0,2.0,120.0,9,2,0,6,0.0,0.0,0,12.0,3.0,1.0
2522,Ștefan RaduROU371986,Ștefan Radu,ROU,37,1986,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,6.0,7.0,78.0,21.0,4.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,7.0,6.0,1.0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,6.0,0.0,0.0,7.0,0.0,0.0,0.0,3.0,12.0,9.0,0.0,0.0,0.0,0.0,5.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0

In [56]:
set_2023 = set(df['temp'])

In [57]:
len(set_2023)

2523

In [58]:
y

,temp,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial
0,Aaron CresswellENG341989,Aaron Cresswell,ENG,34,1989,28,24,2235,0,1,0,0,0.3,0.3,3.7,35.0,145.0,82.0,24.8,21.0,11,12.0,7.0,2.0,12.0,31.0,19.0,11.0,10.0,27,56.0,0.0,1127.0,1448.0,18285.0,8587.0,626.0,670.0,387.0,497.0,100.0,206.0,2.9,40.0,91.0,28.0,15.0,9,1,22.5,4.0,1448.0,1157.0,288.0,40.0,1.0,5.0,133,192.0,56.0,5.0,44.0,1.0,1127.0,3.0,35.0,73.0,43.0,27.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1607.0,97.0,507.0,668.0,438.0,13.0,1607.0,7.0,2.0,4.0,766.0,3497.0,1751.0,26.0,1.0,6.0,6.0,960.0,9,9,2,133,0.0,0.0,0,120.0,28.0,27.0
1,Aaron HickeySCO212002,Aaron Hickey,SCO,21,2002,26,23,1916,0,1,0,0,0.4,0.4,0.4,41.0,81.0,47.0,21.3,38.0,26,27.0,11.0,0.0,18.0,32.0,14.0,7.0,11.0,17,32.0,1.0,695.0,838.0,10995.0,3282.0,373.0,411.0,265.0,310.0,46.0,80.0,0.6,6.0,62.0,13.0,4.0,11,2,21.5,0.0,838.0,743.0,93.0,11.0,2.0,1.0,27,82.0,0.0,0.0,0.0,0.0,695.0,2.0,17.0,20.0,14.0,1.0,1.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1028.0,47.0,328.0,499.0,211.0,21.0,1028.0,45.0,17.0,18.0,616.0,3295.0,1802.0,17.0,3.0,16.0,13.0,624.0,20,35,1,27,0.0,1.0,0,111.0,14.0,22.0
2,Aaron RamseyWAL331990,Aaron Ramsey,WAL,33,1990,27,18,1584,1,1,0,0,2.5,2.5,1.8,29.0,126.0,84.0,17.6,47.0,25,18.0,19.0,10.0,16.0,39.0,23.0,4.0,21.0,17,18.0,1.0,915.0,1088.0,16069.0,3809.0,398.0,431.0,382.0,444.0,100.0,159.0,2.0,28.0,88.0,20.0,3.0,22,6,15.3,1.0,1088.0,998.0,88.0,37.0,5.0,11.0,62,6.0,45.0,16.0,18.0,0.0,915.0,2.0,10.0,62.0,42.0,14.0,0.0,5.0,1.0,0.0,4.0,2.0,1.0,0.0,0.0,1.0,0.0,1279.0,43.0,208.0,723.0,361.0,50.0,1279.0,24.0,14.0,5.0,980.0,4866.0,1934.0,34.0,8.0,24.0,32.0,902.0,23,18,3,62,1.0,0.0,0,115.0,6.0,12.0
3,Aaron Wan-BissakaENG261997,Aaron Wan-Bissaka,ENG,26,1997,19,16,1435,0,0,0,0,1.2,1.2,1.0,41.0,55.0,64.0,15.9,40.0,25,20.0,17.0,3.0,23.0,25.0,2.0,8.0,16.0,22,41.0,0.0,706.0,840.0,9538.0,3292.0,448.0,483.0,194.0,240.0,28.0,44.0,0.9,15.0,48.0,10.0,2.0,10,2,14.7,0.0,840.0,715.0,123.0,4.0,2.0,2.0,14,119.0,0.0,0.0,0.0,0.0,706.0,2.0,22.0,30.0,29.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1026.0,75.0,346.0,400.0,286.0,44.0,1026.0,35.0,17.0,18.0,524.0,2614.0,1370.0,24.0,4.0,14.0,10.0,600.0,11,2,0,14,0.0,0.0,0,73.0,13.0,17.0
4,Aaron ZehnterGER192004,Aaron Zehnter,GER,19,2004,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,Óscar de MarcosESP341989,Óscar de Marcos,ESP,34,1989,37,32,2819,1,6,0,0,0.4,0.4,3.5,76.0,204.0,153.0,31.3,67.0,33,34.0,22.0,11.0,40.0,76.0,36.0,6.0,36.0,29,59.0,0.0,1499.0,1932.0,25216.0,9281.0,749.0,849.0,608.0,764.0,119.0,217.0,4.5,37.0,170.0,50.0,23.0,4,2,20.3,0.0,1932.0,1552.0,372.0,32.0,0.0,11.0,130,340.0,0.0,0.0,0.0,0.0,1499.0,8.0,52.0,75.0,63.0,7.0,1.0,1.0,1.0,2.0,9.0,8.0,0.0,1.0,0.0,0.0,0.0,2218.0,93.0,525.0,1042.0,671.0,34.0,2218.0,31.0,12.0,17.0,1119.0,4785.0,2851.0,68.0,8.0,26.0,19.0,1245.0,43,16,2,130,0.0,0.0,1,198.0,25.0,23.0
2519,Þórir Jóhann HelgasonISL232000,Þórir Jóhann Helgason,ISL,23,2000,12,2,222,0,0,0,0,0.1,0.1,0.4,2.0,2.0,5.0,2.5,2.0,2,1.0,0.0,1.0,2.0,3.0,1.0,1.0,2.0,3,3.0,0.0,55.0,75.0,967.0,363.0,26.0,34.0,19.0,22.0,8.0,15.0,0.3,4.0,2.0,0.0,0.0,2,0,32.6,1.0,75.0,65.0,10.0,2.0,0.0,0.0,10,0.0,6.0,5.0,1.0,0.0,55.0,0.0,0.0,7.0,3.0,3.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,96.0,8.0,25.0,42.0,31.0,3.0,96.0,1.0,0.0,1.0,41.0,181.0,88.0,2.0,1.0,4.0,2.0,50.0,2,2,0,10,0.0,0.0,0,12.0,4.0,7.0
2520,İlkay GündoğanGER331990,İlkay Gündoğan,GER,33,1990,31,27,2353,8,4,0,1,7.5,6.7,3.3,53.0,170.0,124.0,26.1,30.0,18,7.0,13.0,10.0,12.0,33.0,21.0,3.0,15.0,20,13.0,0.0,1374.0,1578.0,21396.0,4941.0,746.0,819.0,492.0,543.0,99.0,130.0,4.4,37.0,143.0,35.0,1.0,53,20,18.1,5.0,1578.0,1519.0,56.0,24.0,18.0,6.0,30,5.0,21.0,7.0,4.0,1.0,1374.0,3.0,27.0,90.0,71.0,7.0,2.0,4.0,4.0,2.0,17.0,13.0,1.0,0.0,1.0,2.0,0.0,1806.0,31.0,243.0,975.0,596.0,88.0,1805.0,42.0,16.0,18.0,1072.0,5457.0,2628.0,44.0,7.0,28.0,27.0,1425.0,23,25,6,30,2.0,0.0,0,155.0,19.0,12.0
2521,Łukasz PorębaPOL232000,Łukasz Poręba,POL,23,2000,10,3,260,0,1,0,0,0.6,0.6,0.7,3.0,20.0,18.0,2.9,5.0,4,2.0,1.0,2.0,2.0,3.0,1.0,0.0,3.0,4,2.0,0.0,116.0,143.0,1866.0,539.0,52.0,63.0,48.0,57.0,9.0,13.0,0.4,5.0,12.0,5.0,2.0,3,0,17.1,0.0,143.0,142.0,1.0,1.0,0.0,0.0,6,0.0,0.0,0.0,0.0,0.0,116.0,0.0,1.0,9.0,8.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,170.0,4.0,20.0,93.0,57.0,1.0,170.0,2.0,1.0,1.0,126.0,625.0,223.0,8.0,0.0,5.0,2.0,120.0,9,2,0,6,0.0,0.0,0,12.0,3.0,1.0
2522,Ștefan RaduROU371986,Ștefan Radu,ROU,37,1986,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,6.0,7.0,78.0,21.0,4.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,7.0,6.0,1.0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,6.0,0.0,0.0,7.0,0.0,0.0,0.0,3.0,12.0,9.0,0.0,0.0,0.0,0.0,5.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0

In [59]:
y.loc[y['Player'] == 'Callum Hudson-Odoi']

,temp,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial
336,Callum Hudson-OdoiENG232000,Callum Hudson-Odoi,ENG,23,2000,14,7,605,0,1,0,0,0.2,0.2,0.8,30.0,31.0,44.0,6.7,5.0,3,4.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,2,4.0,0.0,206.0,248.0,3427.0,782.0,114.0,128.0,67.0,78.0,22.0,30.0,0.9,13.0,18.0,7.0,1.0,4,1,20.4,0.0,248.0,223.0,22.0,8.0,1.0,2.0,12,4.0,4.0,3.0,0.0,0.0,206.0,3.0,6.0,26.0,19.0,4.0,1.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,288.0,6.0,32.0,145.0,117.0,10.0,288.0,28.0,14.0,10.0,193.0,1610.0,893.0,23.0,6.0,7.0,14.0,240.0,2,20,2,12,0.0,0.0,0,26.0,0.0,5.0

## Now After Performing the Merge, We Need to Identify the Position of the Players. For a Transferred Player, the Position of the Player Is Chosen by Identifying the Position That the Player Played the Maximum Time In

In [60]:
#Find Position

for i in range(len(y)):
  t = y.loc[i, 'temp']

  df_t = df.loc[df['temp'] == t, ['Pos', 'Min_Playing']].groupby(['Pos'])['Min_Playing'].sum().reset_index()
  pos = list(df_t['Pos'])
  mins = list(df_t['Min_Playing'])
  max_mins_index = mins.index(max(mins))
  y.loc[i, 'Pos'] = pos[max_mins_index]

In [61]:
y

,temp,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos
0,Aaron CresswellENG341989,Aaron Cresswell,ENG,34,1989,28,24,2235,0,1,0,0,0.3,0.3,3.7,35.0,145.0,82.0,24.8,21.0,11,12.0,7.0,2.0,12.0,31.0,19.0,11.0,10.0,27,56.0,0.0,1127.0,1448.0,18285.0,8587.0,626.0,670.0,387.0,497.0,100.0,206.0,2.9,40.0,91.0,28.0,15.0,9,1,22.5,4.0,1448.0,1157.0,288.0,40.0,1.0,5.0,133,192.0,56.0,5.0,44.0,1.0,1127.0,3.0,35.0,73.0,43.0,27.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1607.0,97.0,507.0,668.0,438.0,13.0,1607.0,7.0,2.0,4.0,766.0,3497.0,1751.0,26.0,1.0,6.0,6.0,960.0,9,9,2,133,0.0,0.0,0,120.0,28.0,27.0,DF
1,Aaron HickeySCO212002,Aaron Hickey,SCO,21,2002,26,23,1916,0,1,0,0,0.4,0.4,0.4,41.0,81.0,47.0,21.3,38.0,26,27.0,11.0,0.0,18.0,32.0,14.0,7.0,11.0,17,32.0,1.0,695.0,838.0,10995.0,3282.0,373.0,411.0,265.0,310.0,46.0,80.0,0.6,6.0,62.0,13.0,4.0,11,2,21.5,0.0,838.0,743.0,93.0,11.0,2.0,1.0,27,82.0,0.0,0.0,0.0,0.0,695.0,2.0,17.0,20.0,14.0,1.0,1.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1028.0,47.0,328.0,499.0,211.0,21.0,1028.0,45.0,17.0,18.0,616.0,3295.0,1802.0,17.0,3.0,16.0,13.0,624.0,20,35,1,27,0.0,1.0,0,111.0,14.0,22.0,DF
2,Aaron RamseyWAL331990,Aaron Ramsey,WAL,33,1990,27,18,1584,1,1,0,0,2.5,2.5,1.8,29.0,126.0,84.0,17.6,47.0,25,18.0,19.0,10.0,16.0,39.0,23.0,4.0,21.0,17,18.0,1.0,915.0,1088.0,16069.0,3809.0,398.0,431.0,382.0,444.0,100.0,159.0,2.0,28.0,88.0,20.0,3.0,22,6,15.3,1.0,1088.0,998.0,88.0,37.0,5.0,11.0,62,6.0,45.0,16.0,18.0,0.0,915.0,2.0,10.0,62.0,42.0,14.0,0.0,5.0,1.0,0.0,4.0,2.0,1.0,0.0,0.0,1.0,0.0,1279.0,43.0,208.0,723.0,361.0,50.0,1279.0,24.0,14.0,5.0,980.0,4866.0,1934.0,34.0,8.0,24.0,32.0,902.0,23,18,3,62,1.0,0.0,0,115.0,6.0,12.0,MF
3,Aaron Wan-BissakaENG261997,Aaron Wan-Bissaka,ENG,26,1997,19,16,1435,0,0,0,0,1.2,1.2,1.0,41.0,55.0,64.0,15.9,40.0,25,20.0,17.0,3.0,23.0,25.0,2.0,8.0,16.0,22,41.0,0.0,706.0,840.0,9538.0,3292.0,448.0,483.0,194.0,240.0,28.0,44.0,0.9,15.0,48.0,10.0,2.0,10,2,14.7,0.0,840.0,715.0,123.0,4.0,2.0,2.0,14,119.0,0.0,0.0,0.0,0.0,706.0,2.0,22.0,30.0,29.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1026.0,75.0,346.0,400.0,286.0,44.0,1026.0,35.0,17.0,18.0,524.0,2614.0,1370.0,24.0,4.0,14.0,10.0,600.0,11,2,0,14,0.0,0.0,0,73.0,13.0,17.0,DF
4,Aaron ZehnterGER192004,Aaron Zehnter,GER,19,2004,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,DF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,Óscar de MarcosESP341989,Óscar de Marcos,ESP,34,1989,37,32,2819,1,6,0,0,0.4,0.4,3.5,76.0,204.0,153.0,31.3,67.0,33,34.0,22.0,11.0,40.0,76.0,36.0,6.0,36.0,29,59.0,0.0,1499.0,1932.0,25216.0,9281.0,749.0,849.0,608.0,764.0,119.0,217.0,4.5,37.0,170.0,50.0,23.0,4,2,20.3,0.0,1932.0,1552.0,372.0,32.0,0.0,11.0,130,340.0,0.0,0.0,0.0,0.0,1499.0,8.0,52.0,75.0,63.0,7.0,1.0,1.0,1.0,2.0,9.0,8.0,0.0,1.0,0.0,0.0,0.0,2218.0,93.0,525.0,1042.0,671.0,34.0,2218.0,31.0,12.0,17.0,1119.0,4785.0,2851.0,68.0,8.0,26.0,19.0,1245.0,43,16,2,130,0.0,0.0,1,198.0,25.0,23.0,DF
2519,Þórir Jóhann HelgasonISL232000,Þórir Jóhann Helgason,ISL,23,2000,12,2,222,0,0,0,0,0.1,0.1,0.4,2.0,2.0,5.0,2.5,2.0,2,1.0,0.0,1.0,2.0,3.0,1.0,1.0,2.0,3,3.0,0.0,55.0,75.0,967.0,363.0,26.0,34.0,19.0,22.0,8.0,15.0,0.3,4.0,2.0,0.0,0.0,2,0,32.6,1.0,75.0,65.0,10.0,2.0,0.0,0.0,10,0.0,6.0,5.0,1.0,0.0,55.0,0.0,0.0,7.0,3.0,3.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,96.0,8.0,25.0,42.0,31.0,3.0,96.0,1.0,0.0,1.0,41.0,181.0,88.0,2.0,1.0,4.0,2.0,50.0,2,2,0,10,0.0,0.0,0,12.0,4.0,7.0,MF
2520,İlkay GündoğanGER331990,İlkay Gündoğan,GER,33,1990,31,27,2353,8,4,0,1,7.5,6.7,3.3,53.0,170.0,124.0,26.1,30.0,18,7.0,13.0,10.0,12.0,33.0,21.0,3.0,15.0,20,13.0,0.0,1374.0,1578.0,21396.0,4941.0,746.0,819.0,492.0,543.0,99.0,130.0,4.4,37.0,143.0,35.0,1.0,53,20,18.1,5.0,1578.0,1519.0,56.0,24.0,18.0,6.0,30,5.0,21.0,7.0,4.0,1.0,1374.0,3.0,27.0,90.0,71.0,7.0,2.0,4.0,4.0,2.0,17.0,13.0,1.0,0.0,1.0,2.0,0.0,1806.0,31.0,243.0,975.0,596.0,88.0,1805.0,42.0,16.0,18.0,1072.0,5457.0,2628.0,44.0,7.0,28.0,27.0,1425.0,23,25,6,30,2.0,0.0,0,155.0,19.0,12.0,MF
2521,Łukasz PorębaPOL232000,Łukasz Poręba,POL,23,2000,10,3,260,0,1,0,0,0.6,0.6,0.7,3.0,20.0,18.0,2.9,5.0,4,2.0,1.0,2.0,2.0,3.0,1.0,0.0,3.0,4,2.0,0.0,116.0,143.0,1866.0,539.0,52.0,63.0,48.0,57.0,9.0,13.0,0.4,5.0,12.0,5.0,2.0,3,0,17.1,0.0,143.0,142.0,1.0,1.0,0.0,0.0,6,0.0,0.0,0.0,0.0,0.0,116.0,0.0,1.0,9.0,8.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,170.0,4.0,20.0,93.0,57.0,1.0,170.0,2.0,1.0,1.0,126.0,625.0,223.0,8.0,0.0,5.0,2.0,120.0,9,2,0,6,0.0,0.0,0,12.0,3.0,1.0,MF
2522,Ștefan RaduROU371986,Ștefan Radu,ROU,37,1986,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,6.0,7.0,78.0,21.0,4.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,7.0,6.0,1.0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,6.0,0.0,0.0,7.0,0.0,0.0,0.0,3.0,12.0,9.0,0.0,0.0,0.0,0.0,5.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,FW

In [62]:
y.loc[y['Player'] == 'Callum Hudson-Odoi']

,temp,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos
336,Callum Hudson-OdoiENG232000,Callum Hudson-Odoi,ENG,23,2000,14,7,605,0,1,0,0,0.2,0.2,0.8,30.0,31.0,44.0,6.7,5.0,3,4.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,2,4.0,0.0,206.0,248.0,3427.0,782.0,114.0,128.0,67.0,78.0,22.0,30.0,0.9,13.0,18.0,7.0,1.0,4,1,20.4,0.0,248.0,223.0,22.0,8.0,1.0,2.0,12,4.0,4.0,3.0,0.0,0.0,206.0,3.0,6.0,26.0,19.0,4.0,1.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,288.0,6.0,32.0,145.0,117.0,10.0,288.0,28.0,14.0,10.0,193.0,1610.0,893.0,23.0,6.0,7.0,14.0,240.0,2,20,2,12,0.0,0.0,0,26.0,0.0,5.0,"FW,MF"

## We Also Identify the Squads That the Player Has Played For. If a Player Was Transferred, Then the ‘Squad’ Variable Will Contain Both Teams That the Player Has Played for Separated by a ‘+’ Symbol.

In [63]:
#Find Squad

for i in range(len(y)):
  t = y.loc[i, 'temp']

  l = df.loc[df['temp'] == t, ['Squad']]
  l_list = list(l['Squad'])

  s = ''

  if len(l_list) == 1:
    s = l_list[0]
  else:
    s = l_list[0] + ' + ' + l_list[1]

  y.loc[i, 'Squad'] = s

## Finally We Drop the ‘Temp’ Variable From the Final Dataframe.

In [64]:
y.drop(columns = ['temp'], inplace = True)
y

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad
0,Aaron Cresswell,ENG,34,1989,28,24,2235,0,1,0,0,0.3,0.3,3.7,35.0,145.0,82.0,24.8,21.0,11,12.0,7.0,2.0,12.0,31.0,19.0,11.0,10.0,27,56.0,0.0,1127.0,1448.0,18285.0,8587.0,626.0,670.0,387.0,497.0,100.0,206.0,2.9,40.0,91.0,28.0,15.0,9,1,22.5,4.0,1448.0,1157.0,288.0,40.0,1.0,5.0,133,192.0,56.0,5.0,44.0,1.0,1127.0,3.0,35.0,73.0,43.0,27.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1607.0,97.0,507.0,668.0,438.0,13.0,1607.0,7.0,2.0,4.0,766.0,3497.0,1751.0,26.0,1.0,6.0,6.0,960.0,9,9,2,133,0.0,0.0,0,120.0,28.0,27.0,DF,West Ham
1,Aaron Hickey,SCO,21,2002,26,23,1916,0,1,0,0,0.4,0.4,0.4,41.0,81.0,47.0,21.3,38.0,26,27.0,11.0,0.0,18.0,32.0,14.0,7.0,11.0,17,32.0,1.0,695.0,838.0,10995.0,3282.0,373.0,411.0,265.0,310.0,46.0,80.0,0.6,6.0,62.0,13.0,4.0,11,2,21.5,0.0,838.0,743.0,93.0,11.0,2.0,1.0,27,82.0,0.0,0.0,0.0,0.0,695.0,2.0,17.0,20.0,14.0,1.0,1.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1028.0,47.0,328.0,499.0,211.0,21.0,1028.0,45.0,17.0,18.0,616.0,3295.0,1802.0,17.0,3.0,16.0,13.0,624.0,20,35,1,27,0.0,1.0,0,111.0,14.0,22.0,DF,Brentford
2,Aaron Ramsey,WAL,33,1990,27,18,1584,1,1,0,0,2.5,2.5,1.8,29.0,126.0,84.0,17.6,47.0,25,18.0,19.0,10.0,16.0,39.0,23.0,4.0,21.0,17,18.0,1.0,915.0,1088.0,16069.0,3809.0,398.0,431.0,382.0,444.0,100.0,159.0,2.0,28.0,88.0,20.0,3.0,22,6,15.3,1.0,1088.0,998.0,88.0,37.0,5.0,11.0,62,6.0,45.0,16.0,18.0,0.0,915.0,2.0,10.0,62.0,42.0,14.0,0.0,5.0,1.0,0.0,4.0,2.0,1.0,0.0,0.0,1.0,0.0,1279.0,43.0,208.0,723.0,361.0,50.0,1279.0,24.0,14.0,5.0,980.0,4866.0,1934.0,34.0,8.0,24.0,32.0,902.0,23,18,3,62,1.0,0.0,0,115.0,6.0,12.0,MF,Nice
3,Aaron Wan-Bissaka,ENG,26,1997,19,16,1435,0,0,0,0,1.2,1.2,1.0,41.0,55.0,64.0,15.9,40.0,25,20.0,17.0,3.0,23.0,25.0,2.0,8.0,16.0,22,41.0,0.0,706.0,840.0,9538.0,3292.0,448.0,483.0,194.0,240.0,28.0,44.0,0.9,15.0,48.0,10.0,2.0,10,2,14.7,0.0,840.0,715.0,123.0,4.0,2.0,2.0,14,119.0,0.0,0.0,0.0,0.0,706.0,2.0,22.0,30.0,29.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1026.0,75.0,346.0,400.0,286.0,44.0,1026.0,35.0,17.0,18.0,524.0,2614.0,1370.0,24.0,4.0,14.0,10.0,600.0,11,2,0,14,0.0,0.0,0,73.0,13.0,17.0,DF,Manchester Utd
4,Aaron Zehnter,GER,19,2004,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,DF,Augsburg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2518,Óscar de Marcos,ESP,34,1989,37,32,2819,1,6,0,0,0.4,0.4,3.5,76.0,204.0,153.0,31.3,67.0,33,34.0,22.0,11.0,40.0,76.0,36.0,6.0,36.0,29,59.0,0.0,1499.0,1932.0,25216.0,9281.0,749.0,849.0,608.0,764.0,119.0,217.0,4.5,37.0,170.0,50.0,23.0,4,2,20.3,0.0,1932.0,1552.0,372.0,32.0,0.0,11.0,130,340.0,0.0,0.0,0.0,0.0,1499.0,8.0,52.0,75.0,63.0,7.0,1.0,1.0,1.0,2.0,9.0,8.0,0.0,1.0,0.0,0.0,0.0,2218.0,93.0,525.0,1042.0,671.0,34.0,2218.0,31.0,12.0,17.0,1119.0,4785.0,2851.0,68.0,8.0,26.0,19.0,1245.0,43,16,2,130,0.0,0.0,1,198.0,25.0,23.0,DF,Athletic Club
2519,Þórir Jóhann Helgason,ISL,23,2000,12,2,222,0,0,0,0,0.1,0.1,0.4,2.0,2.0,5.0,2.5,2.0,2,1.0,0.0,1.0,2.0,3.0,1.0,1.0,2.0,3,3.0,0.0,55.0,75.0,967.0,363.0,26.0,34.0,19.0,22.0,8.0,15.0,0.3,4.0,2.0,0.0,0.0,2,0,32.6,1.0,75.0,65.0,10.0,2.0,0.0,0.0,10,0.0,6.0,5.0,1.0,0.0,55.0,0.0,0.0,7.0,3.0,3.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,96.0,8.0,25.0,42.0,31.0,3.0,96.0,1.0,0.0,1.0,41.0,181.0,88.0,2.0,1.0,4.0,2.0,50.0,2,2,0,10,0.0,0.0,0,12.0,4.0,7.0,MF,Lecce
2520,İlkay Gündoğan,GER,33,1990,31,27,2353,8,4,0,1,7.5,6.7,3.3,53.0,170.0,124.0,26.1,30.0,18,7.0,13.0,10.0,12.0,33.0,21.0,3.0,15.0,20,13.0,0.0,1374.0,1578.0,21396.0,4941.0,746.0,819.0,492.0,543.0,99.0,130.0,4.4,37.0,143.0,35.0,1.0,53,20,18.1,5.0,1578.0,1519.0,56.0,24.0,18.0,6.0,30,5.0,21.0,7.0,4.0,1.0,1374.0,3.0,27.0,90.0,71.0,7.0,2.0,4.0,4.0,2.0,17.0,13.0,1.0,0.0,1.0,2.0,0.0,1806.0,31.0,243.0,975.0,596.0,88.0,1805.0,42.0,16.0,18.0,1072.0,5457.0,2628.0,44.0,7.0,28.0,27.0,1425.0,23,25,6,30,2.0,0.0,0,155.0,19.0,12.0,MF,Manchester City
2521,Łukasz Poręba,POL,23,2000,10,3,260,0,1,0,0,0.6,0.6,0.7,3.0,20.0,18.0,2.9,5.0,4,2.0,1.0,2.0,2.0,3.0,1.0,0.0,3.0,4,2.0,0.0,116.0,143.0,1866.0,539.0,52.0,63.0,48.0,57.0,9.0,13.0,0.4,5.0,12.0,5.0,2.0,3,0,17.1,0.0,143.0,142.0,1.0,1.0,0.0,0.0,6,0.0,0.0,0.0,0.0,0.0,116.0,0.0,1.0,9.0,8.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,170.0,4.0,20.0,93.0,57.0,1.0,170.0,2.0,1.0,1.0,126.0,625.0,223.0,8.0,0.0,5.0,2.0,120.0,9,2,0,6,0.0,0.0,0,12.0,3.0,1.0,MF,Lens
2522,Ștefan Radu,ROU,37,1986,1,0,1,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,6.0,7.0,78.0,21.0,4.0,4.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,7.0,6.0,1.0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,6.0,0.0,0.0,7.0,0.0,0.0,0.0,3.0,12.0,9.0,0.0,0.0,0.0,0.0,5.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,FW,Lazio

In [65]:
y.loc[y['Player'] == 'Jorginho']

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad
1150,Jorginho,ITA,32,1991,32,24,2134,2,1,2,2,1.9,0.3,0.6,28.0,179.0,18.0,23.7,60.0,36,28.0,24.0,8.0,27.0,70.0,43.0,5.0,20.0,30,15.0,0.0,1390.0,1620.0,22800.0,6539.0,658.0,732.0,606.0,682.0,92.0,135.0,1.0,12.0,171.0,21.0,0.0,9,1,56.4,0.0,1620.0,1571.0,44.0,43.0,7.0,5.0,4,1.0,0.0,0.0,0.0,0.0,1390.0,5.0,19.0,50.0,48.0,0.0,0.0,0.0,0.0,2.0,7.0,6.0,0.0,0.0,0.0,0.0,1.0,1833.0,63.0,432.0,1053.0,353.0,16.0,1831.0,22.0,8.0,9.0,1069.0,4730.0,2342.0,39.0,1.0,22.0,17.0,1335.0,18,41,0,4,0.0,0.0,0,188.0,18.0,19.0,MF,Arsenal + Chelsea

##Finally, we save the final dataframe into a .csv file to be used for later.

In [66]:
y.to_csv('Outfielders_Final_EuropeTop5.csv', index = False)