##Now, There Could Be Players Who Were Transferred Between Europe’s Top 5 Leagues and Liga Primeira and Eredivisie. These Players Need to Be Merged.

In [1]:
import pandas as pd
import io
from google.colab import files
uploaded=files.upload()
df1=pd.read_csv(io.BytesIO(uploaded['Outfielders_Final_EuropeTop5.csv']))

Saving Outfielders_Final_EuropeTop5.csv to Outfielders_Final_EuropeTop5.csv

In [2]:
uploaded=files.upload()
df2=pd.read_csv(io.BytesIO(uploaded['Outfielders_Liga_Portugal.csv']))

Saving Outfielders_Liga_Portugal.csv to Outfielders_Liga_Portugal.csv

In [3]:
uploaded=files.upload()
df3=pd.read_csv(io.BytesIO(uploaded['Outfielders_Eredivisie.csv']))

Saving Outfielders_Eredivisie.csv to Outfielders_Eredivisie.csv

##Concatenate all 3 Dataframes

In [4]:
df = pd.concat([df1, df2, df3], ignore_index = True)

In [5]:
pd.set_option('display.max_columns', 500)

In [6]:
df

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad
0,Aaron Cresswell,ENG,34,1989,28.0,24,2235,0,1,0,0,0.3,0.3,3.7,35.0,145.0,82.0,24.8,21.0,11,12.0,7.0,2.0,12.0,31.0,19.0,11.0,10.0,27,56.0,0.0,1127.0,1448.0,18285.0,8587.0,626.0,670.0,387.0,497.0,100.0,206.0,2.9,40.0,91.0,28.0,15.0,9,1,22.5,4.0,1448.0,1157.0,288.0,40.0,1.0,5.0,133,192.0,56.0,5.0,44.0,1.0,1127.0,3.0,35.0,73.0,43.0,27.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1607.0,97.0,507.0,668.0,438.0,13.0,1607.0,7.0,2.0,4.0,766.0,3497.0,1751.0,26.0,1.0,6.0,6.0,960.0,9,9,2,133,0.0,0.0,0,120.0,28.0,27.0,DF,West Ham
1,Aaron Hickey,SCO,21,2002,26.0,23,1916,0,1,0,0,0.4,0.4,0.4,41.0,81.0,47.0,21.3,38.0,26,27.0,11.0,0.0,18.0,32.0,14.0,7.0,11.0,17,32.0,1.0,695.0,838.0,10995.0,3282.0,373.0,411.0,265.0,310.0,46.0,80.0,0.6,6.0,62.0,13.0,4.0,11,2,21.5,0.0,838.0,743.0,93.0,11.0,2.0,1.0,27,82.0,0.0,0.0,0.0,0.0,695.0,2.0,17.0,20.0,14.0,1.0,1.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1028.0,47.0,328.0,499.0,211.0,21.0,1028.0,45.0,17.0,18.0,616.0,3295.0,1802.0,17.0,3.0,16.0,13.0,624.0,20,35,1,27,0.0,1.0,0,111.0,14.0,22.0,DF,Brentford
2,Aaron Ramsey,WAL,33,1990,27.0,18,1584,1,1,0,0,2.5,2.5,1.8,29.0,126.0,84.0,17.6,47.0,25,18.0,19.0,10.0,16.0,39.0,23.0,4.0,21.0,17,18.0,1.0,915.0,1088.0,16069.0,3809.0,398.0,431.0,382.0,444.0,100.0,159.0,2.0,28.0,88.0,20.0,3.0,22,6,15.3,1.0,1088.0,998.0,88.0,37.0,5.0,11.0,62,6.0,45.0,16.0,18.0,0.0,915.0,2.0,10.0,62.0,42.0,14.0,0.0,5.0,1.0,0.0,4.0,2.0,1.0,0.0,0.0,1.0,0.0,1279.0,43.0,208.0,723.0,361.0,50.0,1279.0,24.0,14.0,5.0,980.0,4866.0,1934.0,34.0,8.0,24.0,32.0,902.0,23,18,3,62,1.0,0.0,0,115.0,6.0,12.0,MF,Nice
3,Aaron Wan-Bissaka,ENG,26,1997,19.0,16,1435,0,0,0,0,1.2,1.2,1.0,41.0,55.0,64.0,15.9,40.0,25,20.0,17.0,3.0,23.0,25.0,2.0,8.0,16.0,22,41.0,0.0,706.0,840.0,9538.0,3292.0,448.0,483.0,194.0,240.0,28.0,44.0,0.9,15.0,48.0,10.0,2.0,10,2,14.7,0.0,840.0,715.0,123.0,4.0,2.0,2.0,14,119.0,0.0,0.0,0.0,0.0,706.0,2.0,22.0,30.0,29.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1026.0,75.0,346.0,400.0,286.0,44.0,1026.0,35.0,17.0,18.0,524.0,2614.0,1370.0,24.0,4.0,14.0,10.0,600.0,11,2,0,14,0.0,0.0,0,73.0,13.0,17.0,DF,Manchester Utd
4,Aaron Zehnter,GER,19,2004,1.0,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,DF,Augsburg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3523,Zakaria Bakkali,BEL,27,1996,0.0,1,445,3,0,0,0,1.4,1.4,1.1,31.0,17.0,48.0,4.9,8.0,6,5.0,2.0,1.0,5.0,5.0,0.0,0.0,2.0,2,3.0,0.0,127.0,172.0,1996.0,544.0,68.0,80.0,43.0,53.0,10.0,19.0,1.3,8.0,5.0,10.0,3.0,15,4,19.2,0.0,172.0,157.0,15.0,1.0,1.0,0.0,19,6.0,7.0,3.0,1.0,0.0,127.0,0.0,5.0,14.0,9.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,252.0,8.0,30.0,79.0,150.0,24.0,252.0,34.0,15.0,15.0,158.0,1269.0,640.0,25.0,7.0,12.0,8.0,176.0,4,14,6,19,0.0,0.0,0,20.0,0.0,5.0,"FW,DF",RKC Waalwijk
3524,Zakaria Labyad,MAR,30,1993,0.0,3,249,1,0,0,0,0.3,0.3,0.1,1.0,9.0,13.0,2.8,5.0,4,2.0,3.0,0.0,2.0,9.0,7.0,0.0,3.0,1,0.0,0.0,61.0,93.0,841.0,216.0,33.0,42.0,20.0,27.0,3.0,10.0,0.3,3.0,7.0,3.0,0.0,4,3,17.5,1.0,93.0,88.0,3.0,0.0,1.0,0.0,6,1.0,1.0,0.0,0.0,0.0,61.0,2.0,4.0,8.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,116.0,1.0,13.0,61.0,43.0,6.0,116.0,0.0,0.0,0.0,59.0,152.0,59.0,4.0,0.0,6.0,5.0,80.0,4,1,0,6,0.0,0.0,0,9.0,1.0,1.0,"FW,MF",Utrecht
3525,Zico Buurmeester,NED,21,2002,0.0,0,62,1,0,0,0,0.2,0.2,0.0,0.0,2.0,1.0,0.7,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0,3.0,0.0,34.0,41.0,473.0,210.0,17.0,19.0,13.0,14.0,1.0,4.0,0.0,0.0,5.0,0.0,0.0,1,1,15.9,0.0,41.0,39.0,2.0,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.0,2.0,17.0,22.0,15.0,3.0,54.0,3.0,0.0,3.0,36.0,83.0,15.0,1.0,0.0,1.0,1.0,37.0,3,1,0,0,0.0,0.0,0,8.0,2.0,2.0,MF,AZ Alkmaar
3526,Zinho Vanheusden,BEL,24,1999,0.0,2,225,0,0,0,0,0.1,0.1,0.0,4.0,7.0,2.0,2.5,2.0,0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2,14.0,0.0,102.0,133.0,2042.0,546.0,29.0,36.0,58.0,70.0,15.0,24.0,0.0,0.0,6.0,0.0,0.0,3,1,18.6,0.0,133.0,128.0,4.0,4.0,0.0,1.0,1,0.0,0.0,0.0,0.0,0.0,102.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,158.0,19.0,82.0,69.0,7.0,2.0,158.0,0.0,0.0,0.0,99.0,561.0,285.0,1.0,0.0,0.0,0.0,100.0,3,2,0,1,0.0,1.0,0,18.0,9.0,11.0,DF,AZ Alkmaar
3527,Úmaro Embaló,POR,22,2001,27.0,18,1470,3,3,0,0,1.6,1.6,2.1,45.0,26.0,126.0,16.3,34.0,23,14.0,15.0,5.0,13.0,24.0,11.0,0.0,15.0,8,11.0,0.0,247.0,384.0,3997.0,919.0,125.0,163.0,86.0,132.0,21.0,49.0,2.6,18.0,21.0,11.0,6.0,21,9,17.6,0.0,384.0,372.0,12.0,1.0,2.0,1.0,52,9.0,2.0,1.0,0.0,0.0,247.0,0.0,19.0,36.0,23.0,1.0,5.0,3.0,3.0,1.0,4.0,2.0,1.0,1.0,0.0,0.0,0.0,579.0,16.0,115.0,192.0,283.0,59.0,579.0,56.0,24.0,26.0,353.0,2431.0,1165.0,17.0,20.0,47.0,29.0,366.0,17,23,10,52,0.0,0.0,0,86.0,4.0,8.0,"FW,MF",Fortuna Sittard

##Merging Transferred Players Follows the Same Process. Hence, We Again Create a Custom Primary Key

In [7]:
df['temp'] = df['Player'].map(str) + df['Nation'].map(str) + df['Age'].map(str) + df['Born'].map(str)
df.head()

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad,temp
0,Aaron Cresswell,ENG,34,1989,28.0,24,2235,0,1,0,0,0.3,0.3,3.7,35.0,145.0,82.0,24.8,21.0,11,12.0,7.0,2.0,12.0,31.0,19.0,11.0,10.0,27,56.0,0.0,1127.0,1448.0,18285.0,8587.0,626.0,670.0,387.0,497.0,100.0,206.0,2.9,40.0,91.0,28.0,15.0,9,1,22.5,4.0,1448.0,1157.0,288.0,40.0,1.0,5.0,133,192.0,56.0,5.0,44.0,1.0,1127.0,3.0,35.0,73.0,43.0,27.0,0.0,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1607.0,97.0,507.0,668.0,438.0,13.0,1607.0,7.0,2.0,4.0,766.0,3497.0,1751.0,26.0,1.0,6.0,6.0,960.0,9,9,2,133,0.0,0.0,0,120.0,28.0,27.0,DF,West Ham,Aaron CresswellENG341989
1,Aaron Hickey,SCO,21,2002,26.0,23,1916,0,1,0,0,0.4,0.4,0.4,41.0,81.0,47.0,21.3,38.0,26,27.0,11.0,0.0,18.0,32.0,14.0,7.0,11.0,17,32.0,1.0,695.0,838.0,10995.0,3282.0,373.0,411.0,265.0,310.0,46.0,80.0,0.6,6.0,62.0,13.0,4.0,11,2,21.5,0.0,838.0,743.0,93.0,11.0,2.0,1.0,27,82.0,0.0,0.0,0.0,0.0,695.0,2.0,17.0,20.0,14.0,1.0,1.0,2.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1028.0,47.0,328.0,499.0,211.0,21.0,1028.0,45.0,17.0,18.0,616.0,3295.0,1802.0,17.0,3.0,16.0,13.0,624.0,20,35,1,27,0.0,1.0,0,111.0,14.0,22.0,DF,Brentford,Aaron HickeySCO212002
2,Aaron Ramsey,WAL,33,1990,27.0,18,1584,1,1,0,0,2.5,2.5,1.8,29.0,126.0,84.0,17.6,47.0,25,18.0,19.0,10.0,16.0,39.0,23.0,4.0,21.0,17,18.0,1.0,915.0,1088.0,16069.0,3809.0,398.0,431.0,382.0,444.0,100.0,159.0,2.0,28.0,88.0,20.0,3.0,22,6,15.3,1.0,1088.0,998.0,88.0,37.0,5.0,11.0,62,6.0,45.0,16.0,18.0,0.0,915.0,2.0,10.0,62.0,42.0,14.0,0.0,5.0,1.0,0.0,4.0,2.0,1.0,0.0,0.0,1.0,0.0,1279.0,43.0,208.0,723.0,361.0,50.0,1279.0,24.0,14.0,5.0,980.0,4866.0,1934.0,34.0,8.0,24.0,32.0,902.0,23,18,3,62,1.0,0.0,0,115.0,6.0,12.0,MF,Nice,Aaron RamseyWAL331990
3,Aaron Wan-Bissaka,ENG,26,1997,19.0,16,1435,0,0,0,0,1.2,1.2,1.0,41.0,55.0,64.0,15.9,40.0,25,20.0,17.0,3.0,23.0,25.0,2.0,8.0,16.0,22,41.0,0.0,706.0,840.0,9538.0,3292.0,448.0,483.0,194.0,240.0,28.0,44.0,0.9,15.0,48.0,10.0,2.0,10,2,14.7,0.0,840.0,715.0,123.0,4.0,2.0,2.0,14,119.0,0.0,0.0,0.0,0.0,706.0,2.0,22.0,30.0,29.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1026.0,75.0,346.0,400.0,286.0,44.0,1026.0,35.0,17.0,18.0,524.0,2614.0,1370.0,24.0,4.0,14.0,10.0,600.0,11,2,0,14,0.0,0.0,0,73.0,13.0,17.0,DF,Manchester Utd,Aaron Wan-BissakaENG261997
4,Aaron Zehnter,GER,19,2004,1.0,0,1,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0,0.0,0.0,0.0,DF,Augsburg,Aaron ZehnterGER192004

##Identify the columns whose values are to be aggregated

In [8]:
cols = list(df.columns)[4:-3]

##Identify the Unique Players using the Custom Primary Key

In [10]:
set_temp = list(set(df['temp']))

In [11]:
set_temp

['Emanuel AiwumAUT232000',
 'Dean JamesNED232000',
 'Scott McTominaySCO271996',
 'Dani de WitNED251998',
 'Moussa DiarraMLI232000',
 'Sebastian SzymańskiPOL241999',
 'Simone BastoniITA271996',
 'Jon KarrikaburuESP212002',
 'Papa Ndiaga YadeSEN232000',
 'Felix NmechaGER232000',
 'WeversonBRA232000',
 'Bram NuytinckNED331990',
 'Erick FerigraECU241999',
 'MartinelliBRA222001',
 'Nigel ThomasNED222001',
 'Dennis PraetBEL291994',
 'Ricardo PepiUSA202003',
 'Victor PereaESP232000',
 'Dwight McNeilENG241999',
 'Joshua BrenetNED291994',
 'Tim SkarkeGER271996',
 'Iván BalliuALB311992',
 'Mohamed BouchouariBEL232000',
 'Laros DuarteNED261997',
 'Taylor BoothUSA222001',
 'Iñaki WilliamsGHA291994',
 'Simon Van DuivenboodenNED212002',
 'Arnau PuigmalESP222001',
 'Matúš BeroSVK281995',
 'Nikolai Baden FrederiksenDEN232000',
 'Yusupha NjieGAM291994',
 'Luka LochoshviliGEO251998',
 'André RamalhoBRA311992',
 'Dango OuattaraBFA212002',
 'Alberto GrassiITA281995',
 'Lorenzo MalagridaITA202003',
 'Festy EboseleIRL212002',
 'Igor PaixãoBRA232000',
 'Jordan FerriFRA311992',
 'Jason MbockFRA241999',
 'DaniloBRA222001',
 'Mikael EllertssonISL212002',
 'Aleix GarcíaESP261997',
 'Mohamed ToureAUS192004',
 'Ruslan MalinovskyiUKR301993',
 'Koni De WinterBEL212002',
 'Johan HoveNOR232000',
 'Salim Ben SeghirFRA202003',
 'Giacomo QuagliataITA232000',
 'Ismaëlben BouraFRA232000',
 'Christos TzolisGRE212002',
 'Pedro NetoPOR232000',
 'Steven FortesCPV311992',
 'Mauro JúniorBRA241999',
 'Ethan AmpaduWAL232000',
 'Mato JajaloBIH351988',
 'César MontesMEX261997',
 "N'Golo KantéFRA321991",
 'Bobby ReidJAM301993',
 'Juan CruzESP232000',
 'Miha BlažičSVN301993',
 'Rodrigo MartinsPOR251998',
 'Kieran TrippierENG331990',
 'Alexander SchmidtAUT251998',
 'Bart van RooijNED222001',
 'Houssem AouarFRA251998',
 'Jonas HofmannGER311992',
 'Givairo ReadUnknown172006',
 'Mats KöhlertGER251998',
 'Ozan KabakTUR232000',
 'Paulo DybalaARG301993',
 'Antoine GriezmannFRA321991',
 'Andri Fannar BaldurssonISL212002',
 'Darko ChurlinovMKD232000',
 'Sepp van den BergNED222001',
 'Dikeni SalifouTOG202003',
 'ReinierBRA212002',
 'Rico LewisENG192004',
 'Ivane ChegraFRA192004',
 'Yasser LarouciALG222001',
 'Ivan RadovanovićSRB351988',
 'JosanESP341989',
 'Manfred UgaldeCRC212002',
 'Felix GarretaESP192004',
 'Eliesse Ben SeghirFRA182005',
 'Owen WijndalNED241999',
 'LuquinhaBRA232000',
 'Emil ForsbergSWE321991',
 'Adil RamiFRA381985',
 'Robert WagnerGER202003',
 'Amin SarrSWE222001',
 'Iván MárquezESP291994',
 'Piotr ZielińskiPOL291994',
 'Ante BudimirCRO321991',
 'Darko GyabiENG192004',
 'RicharlisonBRA261997',
 'Ibrahim CissokoNED202003',
 'Daniel VivianESP241999',
 'Julian LelieveldNED261997',
 'Maximiliano CaufriezBEL261997',
 'Hernani InfandePOR222001',
 'Dario Van den BuijsBEL281995',
 'Kévin Keben BiakoloCMR192004',
 'Álvaro djalóESP241999',
 'Mathias OlesenLUX222001',
 'Lameck BandaZAM222001',
 'Mikel MerinoESP271996',
 'Daniel JamesWAL261997',
 'Fernando CaleroESP281995',
 'Kobbie MainooENG182005',
 'Vítor TormenaBRA271996',
 'Jude BellinghamENG202003',
 'Szymon ŻurkowskiPOL261997',
 'Raúl ParraESP241999',
 "Obite N'DickaFRA241999",
 'Léo AndradeBRA251998',
 'Nathan CollinsIRL222001',
 'Noah MbambaBEL182005',
 'Gio ReynaUSA212002',
 'Ruben VargasSUI251998',
 'Steve CookENG321991',
 'Matěj ChalušCZE251998',
 'FaliESP301993',
 'Eldor ShomurodovUZB281995',
 'Josip JuranovićCRO281995',
 'Sondre TronstadNOR281995',
 'Patson DakaZAM251998',
 'Denis HuseinbasicGER222001',
 'Reiss NelsonENG241999',
 'Azor MatusiwaNED251998',
 'Miguel NóbregaPOR232000',
 'Iyenoma UdogieITA212002',
 'Iván RomeroESP222001',
 'Janik HabererGER291994',
 'MagaPOR241999',
 'Magnus MattssonDEN241999',
 'IsmailyBRA331990',
 'Naouirou AhamadaFRA212002',
 'Pablo Galdames MillánCHI271996',
 'Raphael GuzzoPOR281995',
 'Lisandro MagallánARG301993',
 'Daniel AmarteyGHA291994',
 'Wouter GoesNED192004',
 'Niklas TauerGER222001',
 'Jasin AssehnounFIN241999',
 'Radinio BalkerNED251998',
 'Diego NoguerolESP212002',
 'Johann LepenantFRA212002',
 'Anwar El GhaziNED281995',
 'Makoto HasebeJPN391984',
 'Alfa SemedoGNB261997',
 'Marcos AntônioBRA232000',
 'Óscar PlanoESP321991',
 'Jonathan BurkardtGER232000',
 'MarcãoBRA271996',
 'Kiko FemeníaESP321991',
 'Ademola LookmanNGA261997',
 'Filippo BandinelliITA281995',
 'Matheus CunhaBRA241999',
 'Ștefan RaduROU371986',
 'Gelson MartinsPOR281995',
 'Edin DžekoBIH371986',
 'André CastroPOR351988',
 'Cyrille BayalaBFA271996',
 'Rodrigo BentancurURU261997',
 'SerginhoPOR222001',
 'Jérôme BoatengGER351988',
 'Théo TrinkerFRA222001',
 'Marco ReusGER341989',
 "Youssouf M'ChangamaCOM331990",
 'Leonardo SpinazzolaITA301993',
 'Wilson ManafáPOR291994',
 'Declan RiceENG241999',
 'Oscar UreñaESP202003',
 'Thom van BergenNED192004',
 'Julius BeckDEN182005',
 'Martín ZubimendiESP241999',
 'DenílsonBRA281995',
 'Anthony DescotteBEL202003',
 'Victor Bernth KristiansenDEN212002',
 'Pape Cheikh DiopSEN261997',
 'Pasquale MazzocchiITA281995',
 'Luuk BrouwersNED251998',
 'Mikel BalenziagaESP351988',
 'Adama TraoréESP271996',
 'Jacek GóralskiPOL311992',
 'Wilfried ZahaCIV311992',
 'Kenny LalaFRA321991',
 'Mateo TanlongoARG202003',
 'Petar StojanovićSVN281995',
 'Philippe SandlerNED261997',
 'Gaius MakoutaCGO261997',
 'Alexander CallensPER311992',
 'Malang SarrFRA241999',
 'Ilaix MoribaGUI202003',
 'Jesse LingardENG311992',
 'Stevan JovetićMNE341989',
 'Nicolò BarellaITA261997',
 'Maikel KieftenbeldNED331990',
 'Curtis JonesENG222001',
 'Che AdamsSCO271996',
 'Tariq LampteyGHA232000',
 'Gabriel StrefezzaBRA261997',
 'Ibrahima KonéMLI241999',
 'Moise KeanITA232000',
 'Timothy ChandlerUSA331990',
 'João MendesPOR291994',
 'Dario GebuhrGER202003',
 'Marouan AzarkanNED222001',
 'Jean-Manuel MbomGER232000',
 'Brandon SoppyFRA212002',
 'Isak HienSWE241999',
 'Maxime EstèveFRA212002',
 'Dirk AbelsNED261997',
 'Vladimír DaridaCZE331990',
 'Mateo KovačićCRO291994',
 'Dion LopySEN212002',
 'Shurandy SamboNED222001',
 'Mattia ValotiITA301993',
 'Billy van DuijlNED182005',
 'Jean LucasBRA251998',
 'Emiliano MarcondesDEN281995',
 'Mattia De SciglioITA311992',
 'Soichiro KozukiJPN232000',
 'FredBRA301993',
 'Tiemoué BakayokoFRA291994',
 'Alexander MightenENG212002',
 'Jonathan de GuzmánNED361987',
 'Hugo BuenoESP212002',
 'Davide ZappacostaITA311992',
 'Nico ElvediSUI271996',
 'Koffi DjidjiCIV311992',
 'Anthony KhelifaFRA182005',
 'Bamba DiengSEN232000',
 'Ermedin DemirovićBIH251998',
 'Thorgan HazardBEL301993',
 'Alejandro AlfaroESP212002',
 'Romano SchmidAUT232000',
 'Erick GutiérrezMEX281995',
 'Diogo LeitePOR241999',
 'Joe RothwellENG281995',
 'Filippo RomagnaITA261997',
 'GaviESP192004',
 'Rúben FernandesPOR371986',
 'Eduardo FereiraVEN232000',
 'Alfonso EspinoURU311992',
 'Leandro SancaPOR232000',
 'Paolo GhiglioneITA261997',
 'Dimitri LiénardFRA351988',
 'Rocco ReitzGER212002',
 'Tommaso PobegaITA241999',
 'Yoann CathlineFRA212002',
 'Zé FerreiraPOR222001',
 'Alex IwobiNGA271996',
 'Danilo VeigaPOR212002',
 'Willian JoséBRA321991',
 'Theo HernándezFRA261997',
 'Jovane CabralCPV251998',
 'Matt TargettENG281995',
 'Iñigo CórdobaESP261997',
 'Finn StokkersNED271996',
 'Marcos LlorenteESP281995',
 'Robert SkovDEN271996',
 'Héctor BellerínESP281995',
 'Alexandre PenetraPOR222001',
 'Malick ThiawGER222001',
 'Reggie CannonUSA251998',
 'Deron PayneNED212002',
 'Idrissa Gana GueyeSEN341989',
 'Orel MangalaBEL251998',
 'Timo ZaalNED192004',
 'Joao MarcosBRA232000',
 'Ygor NogueiraBRA281995',
 'Joel RocaESP182005',
 'Dodi LukebakioBEL261997',
 'Marcus IngvartsenDEN271996',
 'Youssoufa MoukokoGER192004',
 'Rafael BorréCOL281995',
 'Jetro WillemsNED291994',
 'Nicolas JacksonSEN222001',
 'Daishawn RedanNED222001',
 'Patrik WålemarkSWE222001',
 'Kevin KamplSVN331990',
 'Leandro Barreiro MartinsLUX232000',
 'Paweł BochniewiczPOL271996',
 'João MoutinhoPOR251998',
 'Érik LamelaARG311992',
 'Jonas MartinFRA331990',
 'Matchoi DjalóPOR202003',
 'Bruno OnyemaechiNGA241999',
 'Christian GünterGER301993',
 'Rodrigo AbascalURU291994',
 'Sam BeukemaNED251998',
 'Francesco AntonucciBEL241999',
 'Kevin PinaCPV261997',
 'Mitchell DijksNED301993',
 'Rémy VitaMAD222001',
 'Ryan YatesENG261997',
 'Rubén QuintanillaESP212002',
 'TutaBRA241999',
 'Ansu FatiESP212002',
 'Eric MartelGER212002',
 'Bruno FernandesPOR291994',
 'Anthony MartialFRA281995',
 'Zainadine JúniorMOZ351988',
 'MouraPOR241999',
 'Jamal LoweJAM291994',
 'Falaye SackoMLI281995',
 'Joseph AidooGHA281995',
 'Axel WitselBEL341989',
 'Lucas SoaresBRA251998',
 'Aridane HernándezEQG341989',
 'Kiernan Dewsbury-HallENG251998',
 'DjenéTOG321991',
 'Luca KoleoshoITA192004',
 'Luis SinisterraCOL241999',
 'Josh DoigSCO212002',
 'Mohamed El ArouchFRA192004',
 "Danilo D'AmbrosioITA351988",
 'Fahd MoufiMAR271996',
 'Emmanuel BoatengGHA271996',
 'Jack HinshelwoodENG182005',
 'Roan WilsonCRC212002',
 'Malo GustoFRA202003',
 'Oriol BusquetsESP241999',
 'Alexsandro RibeiroBRA241999',
 'Jon MorcilloESP251998',
 'Myron BoaduNED222001',
 'Kasper DolbergDEN261997',
 'Lukas NmechaGER251998',
 'Hugo MalloESP321991',
 'Guilherme SilvaBRA232000',
 'Boubakary SoumaréFRA241999',
 'Enock MwepuZAM251998',
 'Antonio IervolinoITA202003',
 'Fede San EmeterioESP261997',
 'Vladimír CoufalCZE311992',
 'Nicolás TagliaficoARG311992',
 'Rodrigo ValentePOR222001',
 'Ben ScholteNED222001',
 'Tiago GouveiaPOR222001',
 'Cyriel DessersNGA291994',
 'João CanceloPOR291994',
 'Vitaliy MykolenkoUKR241999',
 'Andoni GorosabelESP271996',
 'Albert Sambi LokongaBEL241999',
 'Fabio QuagliarellaITA401983',
 'Yan ValeryTUN241999',
 'Nelson WeiperGER182005',
 'Kévin DanoisFRA192004',
 'Jodel DossouBEN311992',
 'Arkadiusz MilikPOL291994',
 'Bart RamselaarNED271996',
 'Federico DimarcoITA261997',
 'Ermin BičakčićBIH331990',
 'Sydney van HooijdonkNED232000',
 'Presnel KimpembeFRA281995',
 'Álex FernándezESP311992',
 'Ricardo HortaPOR291994',
 'Florian DietzGER251998',
 'Dani GómezESP251998',
 'ValdemirBRA261997',
 'Sebastian RudyGER331990',
 'Daley SinkgravenNED281995',
 'Ismael SaibariMAR222001',
 'Mike van DuinenNED321991',
 'Angel GomesENG232000',
 'Arijon IbrahimovićGER182005',
 'Arnaud SouquetFRA311992',
 'Kelechi IheanachoNGA271996',
 'Jaidon AnthonyENG241999',
 'Lennerd DaneelsBEL251998',
 'Rami KaibTUN261997',
 'José GrageraESP232000',
 'AlemãoBRA212002',
 'Gauthier HeinFRA271996',
 'Leander DendonckerBEL281995',
 'Ibrahim DiakitéGUI202003',
 'Alexis SánchezCHI351988',
 'Max KruseGER351988',
 'Lucas PerrinFRA251998',
 'Giovani Lo CelsoARG271996',
 'João Othavio BassoBRA261997',
 'Logan CostaCPV222001',
 'Hussein AliSWE212002',
 'Raphaël EyongoNED202003',
 'Calvin StengsNED251998',
 'JeffersonBRA241999',
 'Lucas BernadouFRA232000',
 'Aaron CresswellENG341989',
 'Fran DelgadoESP222001',
 'Leo Augusto PereiraBRA232000',
 'Cristiano RonaldoPOR381985',
 'Manor SolomonISR241999',
 'Djibril SowSUI261997',
 'Jack StaceyENG271996',
 'Alejandro MarquésESP232000',
 'Khalil FayadFRA192004',
 'Abdou DialloSEN271996',
 'Désiré DouéFRA182005',
 'Angelo FulginiFRA271996',
 'Christian MawissaFRA182005',
 'Franco RussoARG291994',
 'Domagoj BradarićCRO241999',
 'Mateusz WieteskaPOL261997',
 'Rodrigo BecãoBRA271996',
 'Thomas KastanarasGRE202003',
 'Fredrik AursnesNOR281995',
 'Fabiano ParisiITA232000',
 'Luca MarroneITA331990',
 'Jérémie BelaANG301993',
 'Brendan ChardonnetFRA291994',
 'Marten de RoonNED321991',
 'Scott McKennaSCO271996',
 'Trent Alexander-ArnoldENG251998',
 'Mattia CaldaraITA291994',
 'Gonçalo GuedesPOR271996',
 'Joe BryanENG301993',
 'Hugo SoteloESP202003',
 'Achraf HakimiMAR251998',
 'David AlabaAUT311992',
 'Andrea CambiasoITA232000',
 'Pascal StruijkNED241999',
 'Rasmus NicolaisenDEN261997',
 'Ruben KluivertNED222001',
 'Nathan Tjoe-A-OnNED222001',
 'RaphinhaBRA271996',
 'PortuESP311992',
 'José FontePOR401983',
 'Duván ZapataCOL321991',
 'Matteo BianchettiITA301993',
 'Darko LazovićSRB331990',
 'Henrique AraújoPOR212002',
 'Mauro ArambarriURU281995',
 'Jorge MeréESP261997',
 'Vicente BesuijenNED222001',
 'Raheem SterlingENG291994',
 'Giulio DonatiITA331990',
 'Leonardo BalerdiARG241999',
 'Joel silvaPOR202003',
 'David PastorBRA232000',
 'Yves BissoumaMLI271996',
 'Antonio SanabriaPAR271996',
 'Naatan SkyttäFIN212002',
 'Mickael MalsaMTQ281995',
 'Souleymane TouréFRA202003',
 'Arnau MartinezESP202003',
 'Anderson JesusBRA281995',
 'Tom BoereNED311992',
 'Adolfo GaichARG241999',
 'João Mário LopesPOR232000',
 'Degnand GnontoITA202003',
 'Marco VerrattiITA311992',
 'Birger MelingNOR291994',
 'Mateus FernandesPOR192004',
 'Aihen MuñozESP261997',
 'Pablo MaffeoESP261997',
 'Adewele SaparaNGA281995',
 'Sandro CruzPOR222001',
 'Riccardo OrsoliniITA261997',
 'Jamie Bynoe-GittensENG192004',
 'Romain FaivreFRA251998',
 'Takahiro KunimotoJPN261997',
 'Adam HložekCZE212002',
 'Diadie SamassékouMLI271996',
 'Sven BotmanNED232000',
 'Yannick GerhardtGER291994',
 'Derry MurkinENG241999',
 'Habib syllaCIV241999',
 'Ben DaviesWAL301993',
 'Yorbe VertessenBEL222001',
 'Lago JuniorCIV331990',
 'Bruno MessiPOR271996',
 'Ardian IsmajliALB271996',
 'Pedro ChirivellaESP261997',
 'Jordan TezeNED241999',
 'José Carlos LazoESP271996',
 'John BrooksUSA301993',
 'Sébastien CorchiaFRA331990',
 'Luuk WoutersNED241999',
 'Pablo MarínESP202003',
 'Diego IturraldeESP202003',
 'Jonathan ClaussFRA311992',
 'Vincenzo GrifoITA301993',
 'Charles-Andréas BrymCAN251998',
 'Bernardo EspinosaCOL341989',
 'Aïman MaurerMAR192004',
 'Marcel SabitzerAUT291994',
 'Clément GrenierFRA321991',
 'Gianluca ScamaccaITA241999',
 'Yanis MassolinFRA212002',
 'Matheus ReisBRA281995',
 'Ricard ArteroESP202003',
 'Luciano VegaARG241999',
 'Antonín BarákCZE291994',
 'Uroš RačićSRB251998',
 'Jimmy CabotFRA291994',
 'Yanis HamacheALG241999',
 'Marc RocaESP271996',
 'David OkerekeNGA261997',
 'Tanguy CoulibalyFRA222001',
 'Ismail JakobsSEN241999',
 'Jaouen HadjamALG202003',
 'Ajdin HrusticAUS271996',
 'Micky van de VenNED222001',
 'Adil AouchicheFRA212002',
 'Almamy TouréMLI271996',
 'Harry ToffoloENG281995',
 'Warren Zaire-EmeryFRA172006',
 'Yvandro Borges SanchesLUX192004',
 'John McGinnSCO291994',
 'Emerson PalmieriITA291994',
 'Mads RoerslevDEN241999',
 'Lorenzo De SilvestriITA351988',
 'Mickaël AlphonseGLP341989',
 'Ohis Felix UduokhaiGER261997',
 'Iñigo MartínezESP321991',
 'Berat DjimsitiALB301993',
 'Pierre KaluluFRA232000',
 'Junya ItoJPN301993',
 'Beñat TurrientesESP212002',
 'Zakaria AboukhlalMAR232000',
 'Otavio AtaideBRA212002',
 'Fabio CarvalhoPOR212002',
 'Filippo RanocchiaITA222001',
 'Samuel Di CarmineITA351988',
 'Suliman MustaphaAUT222001',
 'Jorge Fernando Santos SilvaPOR271996',
 'Veit StangeGER192004',
 'Faouzi GhoulamALG321991',
 'Moussa SyllaFRA241999',
 'Hugo MagnettiFRA251998',
 'Gerard PiquéESP361987',
 'Lucas CunhaBRA261997',
 'Béni MakouanaCGO212002',
 'Mason HolgateENG271996',
 'Arno VerschuerenBEL261997',
 'Raúl GarcíaESP371986',
 'Soungoutou MagassaFRA202003',
 'Dominik KohrGER291994',
 'Felippe CardosoBRA251998',
 'Ole RomenyNED232000',
 'Reda BelahyaneFRA192004',
 'Emmanuel GyasiGHA291994',
 'Teun KoopmeinersNED251998',
 'Daley BlindNED331990',
 'Vitó FerreiraPOR261997',
 'Ckene DoucouréCOM212002',
 'Martin SatrianoURU222001',
 'Rodrigo BattagliaARG321991',
 'Landry DimataBEL261997',
 'Miguel RodríguezESP202003',
 'Tom BischofGER182005',
 'Anthony ModesteFRA351988',
 'Loïc BadeFRA232000',
 'André HahnGER331990',
 'Mamadou TounkaraFRA222001',
 'Vasileios SourlisGRE212002',
 'AngeliñoESP261997',
 'Harry WinksENG271996',
 'Léo BaptistãoBRA311992',
 'Jordi Osei-TutuENG251998',
 'Valentin GendreyFRA232000',
 'Leroy SanéGER271996',
 'Cristian BuonaiutoITA311992',
 'Carlos IsaacESP251998',
 'Omari HutchinsonENG202003',
 'Gabriel VeronBRA212002',
 'Sergio CamelloESP222001',
 'Joshua KitolanoNOR222001',
 'Tim ReamUSA361987',
 'Juan JesusBRA321991',
 'Younes NamliDEN291994',
 'Francis CannGHA251998',
 'Mamady DiarraMLI232000',
 'Thom HayeNED281995',
 'Pape Matar SarrSEN212002',
 'Adam LallanaENG351988',
 'Baila DialloFRA222001',
 'XekaPOR291994',
 'Demba SeckSEN222001',
 'Gian Marco FerrariITA311992',
 'Tiago DjalóPOR232000',
 'Deyovaisio ZeefuikNED251998',
 'Guus TilNED261997',
 'Yunis AbdelhamidMAR361987',
 'James GarnerENG222001',
 'İlkay GündoğanGER331990',
 'Josué SáPOR311992',
 'Sékou Oumar SyllaGUI241999',
 'Tiago EsgaioPOR281995',
 'Boubacar TraoréMLI222001',
 'Josep Antoni GayáESP232000',
 'Jay IdzesNED232000',
 'Samuel Amo-AmeyawENG172006',
 'Nicolas Isimat-MirinFRA321991',
 'Alessandro BiancoITA212002',
 'Yuki SomaJPN261997',
 'Romelu LukakuBEL301993',
 'Sergio LeónESP341989',
 'Pape GueyeSEN241999',
 'Javi PuadoESP251998',
 'Philipp FörsterGER281995',
 'Sebastián Pérez CardonaCOL301993',
 'Casper StaringNED222001',
 'Mimeirhel BenitaNED202003',
 'Metehan GüçlüTUR241999',
 'Vivaldo SemedoPOR182005',
 'Jordan PefokUSA271996',
 'Patrick van AanholtNED331990',
 'Thomas DelaineFRA311992',
 'Fernand MayemboCGO271996',
 'Kristijan JakićCRO261997',
 'Ángel CorreaARG281995',
 'Nicolai RappGER271996',
 'Siriki DembéléCIV271996',
 'Théo PellenardFRA291994',
 'Nicolás Ezequiel FernándezARG232000',
 'Luca de la TorreUSA251998',
 'Elias AchouriTUN241999',
 'Ángel Di MaríaARG351988',
 'Jonathan SchmidFRA331990',
 'Fabien CentonzeFRA271996',
 'Aaron HickeySCO212002',
 'Álvaro MorataESP311992',
 'Mostafa MohamedEGY261997',
 'Bruno WilsonPOR261997',
 'Herculano NabianPOR192004',
 'James Lea SilikiCMR271996',
 'Oussama IdrissiMAR271996',
 'Dani OlmoESP251998',
 'Daan HuismanNED212002',
 'Matheus BabiBRA261997',
 'Bart VriendsNED321991',
 'Peter PekaríkSVK371986',
 'Alassane PléaFRA301993',
 'Jacopo FazziniITA202003',
 'Julien LombotoCOD212002',
 'Juan BrandárizESP241999',
 'Kenji GorréCUW291994',
 'Doğan ErdoğanTUR271996',
 'Ondrej DudaSVK291994',
 'Corentin TolissoFRA291994',
 'Joshua EijgenraamNED222001',
 'Alfred DuncanGHA301993',
 'Juan CuadradoCOL351988',
 'Nahuel MolinaARG251998',
 'Virgil van DijkNED321991',
 'Moises CastilloCOL222001',
 'Álex ColladoESP241999',
 'Marco PašalićCRO232000',
 'Gaëtan PerrinFRA271996',
 'Bertrand TraoréBFA281995',
 'Nélson MontePOR281995',
 'Morgan Gibbs-WhiteENG232000',
 'Mika BierethDEN202003',
 'Leonardo ButaPOR212002',
 'Nathan PattersonSCO222001',
 'Lamine DiabyFRA271996',
 'Álvaro GiménezESP321991',
 'Isaac Palazón CamachoESP291994',
 'Bamidele Isa YusufNGA222001',
 'Sergio BusquetsESP351988',
 'RubénESP222001',
 'Moses YawGHA241999',
 'Jacob RasmussenDEN261997',
 'Edu ExpósitoESP271996',
 'Olivier GiroudFRA371986',
 'Viktor TsyhankovUKR261997',
 'Kenji-Van BotoMAD271996',
 'Lilian BrassierFRA241999',
 'Gianluca GaetanoITA232000',
 'José Manuel VelázquezVEN331990',
 'Leon GoretzkaGER281995',
 'Issa DiopFRA261997',
 'Silas KatompaCOD251998',
 'Carles AleñáESP251998',
 'Veljko BirmančevićSRB251998',
 'Osama RashidIRQ311992',
 'Bradley BarcolaFRA212002',
 'Sven MichelGER331990',
 'Fabio DepaoliITA261997',
 'Mark DiemersNED301993',
 'Ellyes SkhiriTUN281995',
 'Aïssa LaïdouniTUN271996',
 'Jarrod BowenENG271996',
 'Renato SanchesPOR261997',
 'PaulinhoBRA232000',
 'Tyronne EbuehiNGA281995',
 'Davy PröpperNED321991',
 'BruninhoBRA241999',
 'Víctor ChustESP232000',
 'Hakim ZiyechMAR301993',
 'Luka RomeroARG192004',
 'Daniele RuganiITA291994',
 'Cédric HountondjiBEN291994',
 'Serge AurierCIV311992',
 'PepêBRA261997',
 'Nikola MoroCRO251998',
 'Tomáš SoučekCZE281995',
 'Kieffer MooreWAL311992',
 'Dion Drena BeljoCRO212002',
 'Alphonso DaviesCAN232000',
 'RobsonBRA232000',
 'Cristiano BiraghiITA311992',
 'Frederik WintherDEN222001',
 'Flávio NazinhoPOR202003',
 'Pierre Lees-MelouFRA301993',
 'Keziah VeendorpNED261997',
 'Benjamin HenrichsGER261997',
 'Nordine KandilFRA222001',
 'Aaron ZehnterGER192004',
 'Lee KanginKOR222001',
 'Vincent PichelNED222001',
 'Tim OermannGER202003',
 'Julian BrandtGER271996',
 'Rafa MirESP261997',
 'Cristian BorjaCOL301993',
 'HéctorESP281995',
 'Sebastian WalukiewiczPOL232000',
 'NitoGNB212002',
 'Lautaro BlancoARG241999',
 'Pedro David Rosendo MarquesPOR251998',
 'Danny WelbeckENG331990',
 'HenriqueBRA291994',
 'Rhys HealeyWAL291994',
 'Mario LeminaGAB301993',

In [12]:
print(list(df.columns))

['Player', 'Nation', 'Age', 'Born', 'MP_Playing', 'Starts_Playing', 'Min_Playing', 'Gls', 'Ast', 'PK', 'PKatt', 'xG_Expected', 'npxG_Expected', 'xAG_Expected', 'PrgC_Progression', 'PrgP_Progression', 'PrgR_Progression', 'Mins_Per_90', 'Tkl_Tackles', 'TklW_Tackles', 'Def 3rd_Tackles', 'Mid 3rd_Tackles', 'Att 3rd_Tackles', 'Tkl_Challenges', 'Att_Challenges', 'Lost_Challenges', 'Sh_Blocks', 'Pass_Blocks', 'Int', 'Clr', 'Err', 'Cmp_Total', 'Att_Total', 'TotDist_Total', 'PrgDist_Total', 'Cmp_Short', 'Att_Short', 'Cmp_Medium', 'Att_Medium', 'Cmp_Long', 'Att_Long', 'xA', 'KP', 'Final_Third', 'PPA', 'CrsPA', 'Sh_Standard', 'SoT_Standard', 'Dist_Standard', 'FK_Standard', 'Att', 'Live_Pass', 'Dead_Pass', 'FK_Pass', 'TB_Pass', 'Sw_Pass', 'Crs_Pass', 'TI_Pass', 'CK_Pass', 'In_Corner', 'Out_Corner', 'Str_Corner', 'Cmp_Outcomes', 'Off_Outcomes', 'Blocks_Outcomes', 'SCA_SCA', 'PassLive_SCA', 'PassDead_SCA', 'TO_SCA', 'Sh_SCA', 'Fld_SCA', 'Def_SCA', 'GCA_GCA', 'PassLive_GCA', 'PassDead_GCA', 'TO_GCA', 'Sh_GCA', 'Fld_GCA', 'Def_GCA', 'Touches_Touches', 'Def Pen_Touches', 'Def 3rd_Touches', 'Mid 3rd_Touches', 'Att 3rd_Touches', 'Att Pen_Touches', 'Live_Touches', 'Att_Take', 'Succ_Take', 'Tkld_Take', 'Carries_Carries', 'TotDist_Carries', 'PrgDist_Carries', 'Final_Third_Carries', 'CPA_Carries', 'Mis_Carries', 'Dis_Carries', 'Rec_Receiving', 'Fls', 'Fld', 'Off', 'Crs', 'PKwon', 'PKcon', 'OG', 'Recov', 'Won_Aerial', 'Lost_Aerial', 'Pos', 'Squad', 'temp']

## Now we Perform the Merging

In [13]:
X = pd.DataFrame(columns = list(df.columns))

for i in set_temp:
  t = df.loc[df['temp'] == i]

  if len(t) == 1:
    X.loc[len(X)] = list(t.values[0])
  
  if len(t) > 1:
    t1 = t.groupby(['temp', 'Player', 'Nation', 'Age', 'Born'])[cols].sum().reset_index()
    t1_values = list(t1.values[0])[5:]
    t1_squad = ' + '.join(list(t['Squad']))
    t1_temp = i
    t1_player = t1.loc[0, 'Player']
    t1_nation = t1.loc[0, 'Nation']
    t1_age = t1.loc[0, 'Age']
    t1_born = t1.loc[0, 'Born']

    #to find position:
    t2 = t.groupby(['Pos'])['Min_Playing'].sum().reset_index()
    pos_list = list(t2['Pos'])
    mins = list(t2['Min_Playing'])
    max_mins_index = mins.index(max(mins))
    pos = pos_list[max_mins_index]

    #Append to X:
    X.loc[len(X)] = [t1_player, t1_nation, t1_age, t1_born] + t1_values + [pos, t1_squad, t1_temp]

In [14]:
len(X)

3497

In [15]:
len(set_temp)

3497

In [16]:
X

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad,temp
0,Emanuel Aiwum,AUT,23,2000,23.0,17,1653,0,0,0,0,0.2,0.2,0.4,19.0,46.0,7.0,18.4,55.0,34,36.0,17.0,2.0,33.0,47.0,14.0,16.0,12.0,25,52.0,3.0,646.0,817.0,10819.0,3713.0,297.0,332.0,294.0,349.0,40.0,97.0,0.8,4.0,48.0,7.0,1.0,3,1,17.7,0.0,817.0,715.0,100.0,24.0,1.0,6.0,4,67.0,0.0,0.0,0.0,0.0,646.0,2.0,13.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,997.0,105.0,506.0,452.0,51.0,5.0,997.0,10.0,3.0,5.0,500.0,3147.0,1569.0,11.0,0.0,6.0,5.0,521.0,21,15,0,4,0.0,0.0,0,121.0,28.0,17.0,DF,Cremonese,Emanuel AiwumAUT232000
1,Dean James,NED,23,2000,7.0,4,431,0,0,0,0,0.1,0.1,0.1,10.0,10.0,17.0,4.8,10.0,3,7.0,1.0,2.0,8.0,14.0,6.0,1.0,9.0,11,20.0,0.0,117.0,160.0,1963.0,689.0,61.0,68.0,45.0,58.0,10.0,28.0,0.3,3.0,9.0,3.0,1.0,1,0,16.6,0.0,160.0,128.0,31.0,0.0,0.0,4.0,7,31.0,0.0,0.0,0.0,0.0,117.0,1.0,4.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,232.0,22.0,88.0,88.0,63.0,4.0,232.0,9.0,1.0,7.0,105.0,654.0,385.0,6.0,0.0,8.0,7.0,102.0,7,2,0,7,0.0,0.0,0,32.0,3.0,5.0,DF,Volendam,Dean JamesNED232000
2,Scott McTominay,SCO,27,1996,24.0,10,1160,1,0,0,0,1.9,1.9,0.6,20.0,33.0,19.0,12.9,32.0,19,16.0,10.0,6.0,13.0,22.0,9.0,6.0,9.0,14,45.0,0.0,355.0,432.0,5433.0,1549.0,194.0,224.0,122.0,141.0,25.0,36.0,1.0,8.0,32.0,5.0,1.0,13,6,14.9,0.0,432.0,426.0,5.0,3.0,3.0,3.0,4,1.0,0.0,0.0,0.0,0.0,355.0,1.0,6.0,23.0,18.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,618.0,69.0,205.0,287.0,132.0,25.0,618.0,26.0,13.0,9.0,315.0,1610.0,782.0,16.0,3.0,24.0,19.0,359.0,28,16,0,4,0.0,1.0,0,78.0,34.0,23.0,MF,Manchester Utd,Scott McTominaySCO271996
3,Dani de Wit,NED,25,1998,0.0,15,1187,5,0,0,0,3.0,3.0,1.8,4.0,33.0,41.0,13.2,27.0,19,6.0,9.0,12.0,7.0,15.0,8.0,2.0,17.0,11,13.0,0.0,301.0,416.0,3722.0,849.0,192.0,232.0,72.0,112.0,10.0,19.0,2.3,15.0,17.0,7.0,0.0,22,13,11.9,0.0,416.0,404.0,9.0,1.0,3.0,0.0,2,3.0,0.0,0.0,0.0,0.0,301.0,3.0,8.0,22.0,20.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,554.0,19.0,93.0,235.0,228.0,54.0,554.0,5.0,3.0,2.0,238.0,712.0,199.0,9.0,0.0,16.0,9.0,361.0,28,17,3,2,0.0,0.0,0,46.0,41.0,36.0,MF,AZ Alkmaar,Dani de WitNED251998
4,Moussa Diarra,MLI,23,2000,23.0,12,1225,0,1,0,0,0.2,0.2,0.7,21.0,50.0,43.0,13.6,20.0,9,9.0,9.0,2.0,9.0,15.0,6.0,10.0,15.0,19,27.0,1.0,537.0,646.0,8760.0,3452.0,252.0,291.0,235.0,265.0,32.0,51.0,0.6,8.0,30.0,11.0,4.0,1,0,6.4,0.0,646.0,552.0,89.0,21.0,0.0,5.0,13,68.0,0.0,0.0,0.0,0.0,537.0,5.0,15.0,16.0,15.0,0.0,0.0,0.0,1.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,789.0,56.0,296.0,344.0,153.0,8.0,789.0,24.0,9.0,13.0,546.0,3188.0,1480.0,22.0,1.0,23.0,5.0,489.0,19,17,1,13,0.0,1.0,0,69.0,16.0,13.0,DF,Toulouse,Moussa DiarraMLI232000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,Tomáš Suslov,SVK,21,2002,30.0,26,2123,1,1,0,0,2.3,2.3,2.7,42.0,77.0,68.0,23.6,55.0,31,26.0,20.0,9.0,17.0,65.0,48.0,1.0,27.0,25,18.0,1.0,473.0,722.0,9662.0,2586.0,186.0,228.0,197.0,267.0,83.0,174.0,3.4,30.0,52.0,23.0,6.0,55,17,25.5,6.0,722.0,637.0,83.0,35.0,4.0,17.0,91,5.0,36.0,28.0,4.0,0.0,473.0,2.0,23.0,74.0,36.0,11.0,11.0,5.0,9.0,2.0,4.0,3.0,0.0,0.0,0.0,1.0,0.0,1091.0,32.0,201.0,489.0,427.0,42.0,1091.0,114.0,52.0,46.0,621.0,3833.0,1580.0,28.0,10.0,78.0,44.0,613.0,32,63,2,91,1.0,0.0,0,153.0,13.0,20.0,"MF,FW",Groningen,Tomáš SuslovSVK212002
3493,Mathias Kjølø,NOR,22,2001,0.0,11,1004,0,1,0,0,0.8,0.8,0.5,9.0,62.0,18.0,11.2,14.0,9,8.0,4.0,2.0,6.0,10.0,4.0,3.0,11.0,8,19.0,0.0,452.0,556.0,7788.0,2066.0,215.0,256.0,185.0,213.0,38.0,55.0,0.9,7.0,58.0,8.0,1.0,9,3,19.5,0.0,556.0,549.0,5.0,3.0,1.0,6.0,7,2.0,0.0,0.0,0.0,0.0,452.0,2.0,7.0,26.0,24.0,0.0,0.0,0.0,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,668.0,25.0,130.0,368.0,176.0,9.0,668.0,9.0,1.0,3.0,375.0,1315.0,501.0,11.0,2.0,12.0,10.0,432.0,6,13,0,7,0.0,0.0,0,70.0,10.0,15.0,MF,Twente,Mathias KjøløNOR222001
3494,Helibelton Palacios,COL,30,1993,24.0,23,1915,0,0,0,0,0.4,0.4,0.7,25.0,51.0,25.0,21.3,38.0,20,21.0,15.0,2.0,19.0,26.0,7.0,12.0,14.0,20,55.0,0.0,623.0,835.0,10355.0,5114.0,309.0,344.0,245.0,320.0,54.0,126.0,0.9,7.0,49.0,7.0,4.0,4,3,13.8,0.0,835.0,672.0,162.0,18.0,0.0,4.0,18,144.0,0.0,0.0,0.0,0.0,623.0,1.0,20.0,21.0,18.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1030.0,82.0,427.0,497.0,122.0,9.0,1030.0,28.0,14.0,10.0,508.0,2535.0,1514.0,17.0,0.0,10.0,7.0,516.0,30,19,0,18,0.0,0.0,0,118.0,21.0,25.0,DF,Elche,Helibelton PalaciosCOL301993
3495,Mathis Hamdi,FRA,20,2003,2.0,0,69,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0,0.8,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,1.0,0.0,26.0,38.0,347.0,111.0,14.0,18.0,11.0,15.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0,0,0.0,0.0,38.0,27.0,11.0,0.0,0.0,1.0,2,11.0,0.0,0.0,0.0,0.0,26.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0,2.0,14.0,16.0,14.0,0.0,44.0,1.0,0.0,1.0,28.0,186.0,28.0,0.0,0.0,2.0,0.0,27.0,1,1,0,2,0.0,0.0,0,1.0,0.0,1.0,DF,Troyes,Mathis HamdiFRA202003
3496,Abdallah Sima,SEN,22,2001,34.0,19,1836,5,1,0,0,4.8,4.8,2.2,38.0,21.0,140.0,20.4,22.0,13,4.0,15.0,3.0,7.0,19.0,12.0,0.0,8.0,4,19.0,0.0,274.0,374.0,3603.0,688.0,142.0,182.0,84.0,116.0,8.0,17.0,1.3,16.0,18.0,6.0,1.0,39,10,12.7,0.0,374.0,334.0,39.0,0.0,1.0,1.0,16,6.0,0.0,0.0,0.0,0.0,274.0,1.0,15.0,34.0,24.0,0.0,1.0,4.0,5.0,0.0,7.0,2.0,0.0,1.0,1.0,3.0,0.0,589.0,23.0,54.0,271.0,281.0,78.0,589.0,50.0,21.0,25.0,404.0,2855.0,915.0,25.0,17.0,60.0,31.0,424.0,32,24,12,16,1.0,1.0,1,52.0,43.0,63.0,FW,Angers,Abdallah SimaSEN222001

##Discard the Custom Primary Key

In [17]:
X.drop(columns = ['temp'], inplace = True)

In [19]:
X

,Player,Nation,Age,Born,MP_Playing,Starts_Playing,Min_Playing,Gls,Ast,PK,PKatt,xG_Expected,npxG_Expected,xAG_Expected,PrgC_Progression,PrgP_Progression,PrgR_Progression,Mins_Per_90,Tkl_Tackles,TklW_Tackles,Def 3rd_Tackles,Mid 3rd_Tackles,Att 3rd_Tackles,Tkl_Challenges,Att_Challenges,Lost_Challenges,Sh_Blocks,Pass_Blocks,Int,Clr,Err,Cmp_Total,Att_Total,TotDist_Total,PrgDist_Total,Cmp_Short,Att_Short,Cmp_Medium,Att_Medium,Cmp_Long,Att_Long,xA,KP,Final_Third,PPA,CrsPA,Sh_Standard,SoT_Standard,Dist_Standard,FK_Standard,Att,Live_Pass,Dead_Pass,FK_Pass,TB_Pass,Sw_Pass,Crs_Pass,TI_Pass,CK_Pass,In_Corner,Out_Corner,Str_Corner,Cmp_Outcomes,Off_Outcomes,Blocks_Outcomes,SCA_SCA,PassLive_SCA,PassDead_SCA,TO_SCA,Sh_SCA,Fld_SCA,Def_SCA,GCA_GCA,PassLive_GCA,PassDead_GCA,TO_GCA,Sh_GCA,Fld_GCA,Def_GCA,Touches_Touches,Def Pen_Touches,Def 3rd_Touches,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Att_Take,Succ_Take,Tkld_Take,Carries_Carries,TotDist_Carries,PrgDist_Carries,Final_Third_Carries,CPA_Carries,Mis_Carries,Dis_Carries,Rec_Receiving,Fls,Fld,Off,Crs,PKwon,PKcon,OG,Recov,Won_Aerial,Lost_Aerial,Pos,Squad
0,Emanuel Aiwum,AUT,23,2000,23.0,17,1653,0,0,0,0,0.2,0.2,0.4,19.0,46.0,7.0,18.4,55.0,34,36.0,17.0,2.0,33.0,47.0,14.0,16.0,12.0,25,52.0,3.0,646.0,817.0,10819.0,3713.0,297.0,332.0,294.0,349.0,40.0,97.0,0.8,4.0,48.0,7.0,1.0,3,1,17.7,0.0,817.0,715.0,100.0,24.0,1.0,6.0,4,67.0,0.0,0.0,0.0,0.0,646.0,2.0,13.0,11.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,997.0,105.0,506.0,452.0,51.0,5.0,997.0,10.0,3.0,5.0,500.0,3147.0,1569.0,11.0,0.0,6.0,5.0,521.0,21,15,0,4,0.0,0.0,0,121.0,28.0,17.0,DF,Cremonese
1,Dean James,NED,23,2000,7.0,4,431,0,0,0,0,0.1,0.1,0.1,10.0,10.0,17.0,4.8,10.0,3,7.0,1.0,2.0,8.0,14.0,6.0,1.0,9.0,11,20.0,0.0,117.0,160.0,1963.0,689.0,61.0,68.0,45.0,58.0,10.0,28.0,0.3,3.0,9.0,3.0,1.0,1,0,16.6,0.0,160.0,128.0,31.0,0.0,0.0,4.0,7,31.0,0.0,0.0,0.0,0.0,117.0,1.0,4.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,232.0,22.0,88.0,88.0,63.0,4.0,232.0,9.0,1.0,7.0,105.0,654.0,385.0,6.0,0.0,8.0,7.0,102.0,7,2,0,7,0.0,0.0,0,32.0,3.0,5.0,DF,Volendam
2,Scott McTominay,SCO,27,1996,24.0,10,1160,1,0,0,0,1.9,1.9,0.6,20.0,33.0,19.0,12.9,32.0,19,16.0,10.0,6.0,13.0,22.0,9.0,6.0,9.0,14,45.0,0.0,355.0,432.0,5433.0,1549.0,194.0,224.0,122.0,141.0,25.0,36.0,1.0,8.0,32.0,5.0,1.0,13,6,14.9,0.0,432.0,426.0,5.0,3.0,3.0,3.0,4,1.0,0.0,0.0,0.0,0.0,355.0,1.0,6.0,23.0,18.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,618.0,69.0,205.0,287.0,132.0,25.0,618.0,26.0,13.0,9.0,315.0,1610.0,782.0,16.0,3.0,24.0,19.0,359.0,28,16,0,4,0.0,1.0,0,78.0,34.0,23.0,MF,Manchester Utd
3,Dani de Wit,NED,25,1998,0.0,15,1187,5,0,0,0,3.0,3.0,1.8,4.0,33.0,41.0,13.2,27.0,19,6.0,9.0,12.0,7.0,15.0,8.0,2.0,17.0,11,13.0,0.0,301.0,416.0,3722.0,849.0,192.0,232.0,72.0,112.0,10.0,19.0,2.3,15.0,17.0,7.0,0.0,22,13,11.9,0.0,416.0,404.0,9.0,1.0,3.0,0.0,2,3.0,0.0,0.0,0.0,0.0,301.0,3.0,8.0,22.0,20.0,0.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,554.0,19.0,93.0,235.0,228.0,54.0,554.0,5.0,3.0,2.0,238.0,712.0,199.0,9.0,0.0,16.0,9.0,361.0,28,17,3,2,0.0,0.0,0,46.0,41.0,36.0,MF,AZ Alkmaar
4,Moussa Diarra,MLI,23,2000,23.0,12,1225,0,1,0,0,0.2,0.2,0.7,21.0,50.0,43.0,13.6,20.0,9,9.0,9.0,2.0,9.0,15.0,6.0,10.0,15.0,19,27.0,1.0,537.0,646.0,8760.0,3452.0,252.0,291.0,235.0,265.0,32.0,51.0,0.6,8.0,30.0,11.0,4.0,1,0,6.4,0.0,646.0,552.0,89.0,21.0,0.0,5.0,13,68.0,0.0,0.0,0.0,0.0,537.0,5.0,15.0,16.0,15.0,0.0,0.0,0.0,1.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,789.0,56.0,296.0,344.0,153.0,8.0,789.0,24.0,9.0,13.0,546.0,3188.0,1480.0,22.0,1.0,23.0,5.0,489.0,19,17,1,13,0.0,1.0,0,69.0,16.0,13.0,DF,Toulouse
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,Tomáš Suslov,SVK,21,2002,30.0,26,2123,1,1,0,0,2.3,2.3,2.7,42.0,77.0,68.0,23.6,55.0,31,26.0,20.0,9.0,17.0,65.0,48.0,1.0,27.0,25,18.0,1.0,473.0,722.0,9662.0,2586.0,186.0,228.0,197.0,267.0,83.0,174.0,3.4,30.0,52.0,23.0,6.0,55,17,25.5,6.0,722.0,637.0,83.0,35.0,4.0,17.0,91,5.0,36.0,28.0,4.0,0.0,473.0,2.0,23.0,74.0,36.0,11.0,11.0,5.0,9.0,2.0,4.0,3.0,0.0,0.0,0.0,1.0,0.0,1091.0,32.0,201.0,489.0,427.0,42.0,1091.0,114.0,52.0,46.0,621.0,3833.0,1580.0,28.0,10.0,78.0,44.0,613.0,32,63,2,91,1.0,0.0,0,153.0,13.0,20.0,"MF,FW",Groningen
3493,Mathias Kjølø,NOR,22,2001,0.0,11,1004,0,1,0,0,0.8,0.8,0.5,9.0,62.0,18.0,11.2,14.0,9,8.0,4.0,2.0,6.0,10.0,4.0,3.0,11.0,8,19.0,0.0,452.0,556.0,7788.0,2066.0,215.0,256.0,185.0,213.0,38.0,55.0,0.9,7.0,58.0,8.0,1.0,9,3,19.5,0.0,556.0,549.0,5.0,3.0,1.0,6.0,7,2.0,0.0,0.0,0.0,0.0,452.0,2.0,7.0,26.0,24.0,0.0,0.0,0.0,2.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,668.0,25.0,130.0,368.0,176.0,9.0,668.0,9.0,1.0,3.0,375.0,1315.0,501.0,11.0,2.0,12.0,10.0,432.0,6,13,0,7,0.0,0.0,0,70.0,10.0,15.0,MF,Twente
3494,Helibelton Palacios,COL,30,1993,24.0,23,1915,0,0,0,0,0.4,0.4,0.7,25.0,51.0,25.0,21.3,38.0,20,21.0,15.0,2.0,19.0,26.0,7.0,12.0,14.0,20,55.0,0.0,623.0,835.0,10355.0,5114.0,309.0,344.0,245.0,320.0,54.0,126.0,0.9,7.0,49.0,7.0,4.0,4,3,13.8,0.0,835.0,672.0,162.0,18.0,0.0,4.0,18,144.0,0.0,0.0,0.0,0.0,623.0,1.0,20.0,21.0,18.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1030.0,82.0,427.0,497.0,122.0,9.0,1030.0,28.0,14.0,10.0,508.0,2535.0,1514.0,17.0,0.0,10.0,7.0,516.0,30,19,0,18,0.0,0.0,0,118.0,21.0,25.0,DF,Elche
3495,Mathis Hamdi,FRA,20,2003,2.0,0,69,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0,0.8,0.0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1,1.0,0.0,26.0,38.0,347.0,111.0,14.0,18.0,11.0,15.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0,0,0.0,0.0,38.0,27.0,11.0,0.0,0.0,1.0,2,11.0,0.0,0.0,0.0,0.0,26.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44.0,2.0,14.0,16.0,14.0,0.0,44.0,1.0,0.0,1.0,28.0,186.0,28.0,0.0,0.0,2.0,0.0,27.0,1,1,0,2,0.0,0.0,0,1.0,0.0,1.0,DF,Troyes
3496,Abdallah Sima,SEN,22,2001,34.0,19,1836,5,1,0,0,4.8,4.8,2.2,38.0,21.0,140.0,20.4,22.0,13,4.0,15.0,3.0,7.0,19.0,12.0,0.0,8.0,4,19.0,0.0,274.0,374.0,3603.0,688.0,142.0,182.0,84.0,116.0,8.0,17.0,1.3,16.0,18.0,6.0,1.0,39,10,12.7,0.0,374.0,334.0,39.0,0.0,1.0,1.0,16,6.0,0.0,0.0,0.0,0.0,274.0,1.0,15.0,34.0,24.0,0.0,1.0,4.0,5.0,0.0,7.0,2.0,0.0,1.0,1.0,3.0,0.0,589.0,23.0,54.0,271.0,281.0,78.0,589.0,50.0,21.0,25.0,404.0,2855.0,915.0,25.0,17.0,60.0,31.0,424.0,32,24,12,16,1.0,1.0,1,52.0,43.0,63.0,FW,Angers

In [20]:
X.to_csv('Outfielders_Final.csv', index = False)